import {useEffect,useState} from 'react';
import {FiDownload,FiEdit2,FiMessageCircle,FiPaperclip,FiPlus,FiRefreshCw,FiSend,FiSettings,FiTrash2,FiUsers,FiX} from 'react-icons/fi';
import {chatApi} from '../../api/services';
import '../../styles/internal-chat.css';
const labels={GENERAL:'Trao đổi chung',INCIDENT:'Báo cáo vệ sinh',INVENTORY:'Báo cáo hàng hóa',SHIFT_HANDOVER:'Bàn giao ca',ANNOUNCEMENT:'Thông báo',SCHEDULE:'Lịch làm việc'};
const vnDate=value=>new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}).format(new Date(value));
const vnTime=value=>new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
const initials=name=>String(name||'?').trim().split(/\s+/).slice(-2).map(x=>x[0]).join('').toUpperCase();
function ChatAttachment({attachment,onError}){const [url,setUrl]=useState('');useEffect(()=>{let active=true,objectUrl;chatApi.attachment(attachment.attachmentId).then(blob=>{objectUrl=URL.createObjectURL(blob);if(active)setUrl(objectUrl)}).catch(()=>onError?.('Không tải được ảnh đính kèm'));return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[attachment.attachmentId]);const image=String(attachment.mimeType||'').startsWith('image/');if(image)return url?<a className="chat-image-link" href={url} target="_blank" rel="noreferrer"><img className="chat-image" src={url} alt={attachment.originalName}/></a>:<span className="chat-image-loading">Đang tải ảnh...</span>;return <button className="chat-attachment" onClick={async()=>{try{const blob=await chatApi.attachment(attachment.attachmentId),downloadUrl=URL.createObjectURL(blob),link=document.createElement('a');link.href=downloadUrl;link.download=attachment.originalName;link.click();URL.revokeObjectURL(downloadUrl)}catch{onError?.('Không tải được tệp')}}}><FiDownload/><span>{attachment.originalName}</span><small>{Math.ceil(attachment.fileSize/1024)} KB</small></button>}
export default function InternalChatPage(){
 let role=localStorage.getItem('role'),currentUserId;try{const token=localStorage.getItem('token'),p=token?JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))):{};currentUserId=p.userId;role=role||p.role}catch{}
 const [channels,setChannels]=useState([]),[active,setActive]=useState(),[messages,setMessages]=useState([]),[text,setText]=useState(''),[file,setFile]=useState(null),[error,setError]=useState(''),[sending,setSending]=useState(false),[settings,setSettings]=useState(false),[memberChannel,setMemberChannel]=useState(null),[members,setMembers]=useState([]),[newChannel,setNewChannel]=useState({branchId:'',name:''});
 const selected=channels.find(x=>Number(x.channelId)===Number(active)),groups=Object.entries(channels.reduce((o,c)=>{(o[c.branchName]??=[]).push(c);return o},{}));
 async function loadChannels(){try{const r=await chatApi.channels(),list=r.data||[];setChannels(list);setActive(v=>list.some(x=>Number(x.channelId)===Number(v))?v:list[0]?.channelId)}catch(e){setError(e.response?.data?.message||'Không tải được cuộc trò chuyện')}}
 async function loadMessages(id=active){if(!id)return;try{const r=await chatApi.messages(id);setMessages(r.data||[]);await chatApi.read(id)}catch(e){setError(e.response?.data?.message||'Không tải được tin nhắn')}}
 useEffect(()=>{loadChannels()},[]);useEffect(()=>{loadMessages()},[active]);
 useEffect(()=>{const token=localStorage.getItem('token');if(!token)return;let ws,timer,closed=false;const connect=()=>{const protocol=location.protocol==='https:'?'wss':'ws',configured=import.meta.env.VITE_API_WS_PORT,target=configured?`${location.hostname}:${configured}`:location.protocol==='https:'?location.host:`${location.hostname}:5000`;ws=new WebSocket(`${protocol}://${target}/ws/chat`,['chat',token]);ws.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type==='channels_changed')loadChannels();if(Number(d.channelId)===Number(active))loadMessages(active);else if(d.type==='message_created')loadChannels()}catch{}};ws.onclose=()=>{if(!closed)timer=setTimeout(connect,2500)}};connect();return()=>{closed=true;clearTimeout(timer);ws?.close()}},[active]);
 async function send(e){e.preventDefault();if((!text.trim()&&!file)||!active)return;try{setSending(true);await chatApi.send(active,{content:text.trim(),file});setText('');setFile(null);await loadMessages()}catch(err){setError(err.response?.data?.message||'Không gửi được tin nhắn')}finally{setSending(false)}}
 async function create(e){e.preventDefault();try{const r=await chatApi.createChannel(newChannel);setNewChannel({branchId:'',name:''});await loadChannels();setActive(r.data.channelId)}catch(err){setError(err.response?.data?.message||'Không tạo được cuộc trò chuyện')}}
 async function rename(c){const name=prompt('Tên cuộc trò chuyện mới',c.name);if(name?.trim()){await chatApi.updateChannel(c.channelId,name.trim());loadChannels()}}
 async function removeChannel(c){if(confirm(`Xóa cuộc trò chuyện “${c.name}”?`)){await chatApi.removeChannel(c.channelId);loadChannels()}}
 async function editMembers(c){const r=await chatApi.members(c.channelId);setMembers(r.data||[]);setMemberChannel(c)}
 async function saveMembers(){await chatApi.saveMembers(memberChannel.channelId,members.filter(x=>x.isMember).map(x=>x.userId));setMemberChannel(null);loadChannels()}
 return <div className="internal-chat card"><aside><header><b>Chat nội bộ</b><span className="chat-header-actions">{['admin','manager'].includes(role)&&<button onClick={()=>setSettings(true)}><FiSettings/></button>}<button onClick={loadChannels}><FiRefreshCw/></button></span></header>{groups.map(([name,items])=><div className="chat-branch" key={name}><strong>{name}</strong>{items.map(c=><button className={Number(c.channelId)===Number(active)?'active':''} key={c.channelId} onClick={()=>setActive(c.channelId)}><FiMessageCircle/><span>{c.isSystem?(labels[c.channelType]||c.name):c.name}</span>{c.unreadCount>0&&<b>{c.unreadCount}</b>}</button>)}</div>)}</aside><section><header><div><b>{selected?(selected.isSystem?labels[selected.channelType]:selected.name):'Chọn cuộc trò chuyện'}</b><small>{selected?.branchName}</small></div></header>{error&&<div className="manager-form-error">{error}</div>}<div className="chat-messages">{messages.length?messages.map((m,i)=>{const mine=Number(m.senderUserId)===Number(currentUserId),prev=messages[i-1],continued=prev&&Number(prev.senderUserId)===Number(m.senderUserId)&&vnDate(prev.createdAt)===vnDate(m.createdAt),showDay=!prev||vnDate(prev.createdAt)!==vnDate(m.createdAt);return <div className="chat-entry" key={m.messageId}>{showDay&&<div className="chat-day"><span>{vnDate(m.createdAt)}</span></div>}<div className={`chat-line ${mine?'mine':'theirs'} ${continued?'continued':''}`}>{!mine&&!continued&&(m.senderAvatarUrl?<img src={m.senderAvatarUrl}/>:<i>{initials(m.senderName)}</i>)}{!mine&&continued&&<i className="avatar-space"/>}<article>{!mine&&!continued&&<b>{m.senderName}</b>}<p>{m.content}</p>{m.attachments?.map(a=><ChatAttachment key={a.attachmentId} attachment={a} onError={setError}/>) }<time>{vnTime(m.createdAt)}</time></article></div></div>}):<div className="empty-state">Chưa có tin nhắn</div>}</div><form onSubmit={send}><label className="chat-file-button"><FiPaperclip/><input type="file" onChange={e=>setFile(e.target.files[0]||null)}/></label><textarea rows="1" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')e.currentTarget.form.requestSubmit()}} placeholder={file?file.name:'Nhập nội dung trao đổi...'} maxLength="2000"/><button className="btn btn-yellow" disabled={sending||!active}><FiSend/> Gửi</button></form></section>
 {settings&&<div className="chat-settings-backdrop"><div className="chat-settings-panel"><header><div><b>Cài đặt chat</b><small>Tạo, sửa, xóa và quản lý thành viên</small></div><button onClick={()=>setSettings(false)}><FiX/></button></header><form className="chat-create-form" onSubmit={create}><h3><FiPlus/> Tạo cuộc trò chuyện</h3><label>Chi nhánh<select required value={newChannel.branchId} onChange={e=>setNewChannel(v=>({...v,branchId:e.target.value}))}><option value="">Chọn chi nhánh</option>{groups.map(([name,items])=><option key={name} value={items[0].branchId}>{name}</option>)}</select></label><label>Tên<input required minLength="2" maxLength="150" value={newChannel.name} onChange={e=>setNewChannel(v=>({...v,name:e.target.value}))}/></label><button><FiPlus/> Tạo</button></form><div className="chat-manage-list">{channels.filter(c=>!c.isSystem).map(c=><div key={c.channelId}><span><b>{c.name}</b><small>{c.branchName}</small></span><button onClick={()=>rename(c)}><FiEdit2/></button><button onClick={()=>editMembers(c)}><FiUsers/></button><button onClick={()=>removeChannel(c)}><FiTrash2/></button></div>)}</div></div></div>}
 {memberChannel&&<div className="chat-settings-backdrop"><div className="chat-settings-panel"><header><div><b>Thành viên: {memberChannel.name}</b></div><button onClick={()=>setMemberChannel(null)}><FiX/></button></header><div className="chat-member-list">{members.map((m,i)=><label key={m.userId}><input type="checkbox" checked={Boolean(m.isMember)} onChange={e=>setMembers(v=>v.map((x,n)=>n===i?{...x,isMember:e.target.checked}:x))}/><span><b>{m.fullName}</b><small>{m.employeeCode}</small></span></label>)}</div><button className="btn btn-yellow" onClick={saveMembers}>Lưu thành viên</button></div></div>}</div>;
}
