const {sql,getPool}=require("../config/db"),{employeeFromJwt}=require("../services/shiftEligibilityService");const fail=(r,s,m)=>r.status(s).json({success:false,message:m});
async function branch(req,p){const e=await employeeFromJwt(p,req.user.userId);return req.user.role==='admin'?null:e?.branchId}
async function channels(req,res,next){try{const p=await getPool(),b=await branch(req,p),q=p.request();if(b)q.input("b",sql.Int,b);const r=await q.query(`SELECT c.id channelId,c.branch_id branchId,c.channel_type channelType,c.name,(SELECT COUNT(*) FROM chat_messages m WHERE m.channel_id=c.id AND m.is_deleted=0 AND m.id>COALESCE((SELECT last_read_message_id FROM chat_read_states rs WHERE rs.channel_id=c.id AND rs.user_id=${Number(req.user.userId)}),0)) unreadCount FROM chat_channels c WHERE c.is_active=1 AND c.is_test=1${b?' AND c.branch_id=@b':''} ORDER BY c.channel_type`);res.json({success:true,data:r.recordset})}catch(e){next(e)}}
async function allowed(req,p,id){const b=await branch(req,p),r=await p.request().input("id",sql.Int,id).query("SELECT TOP 1 id,branch_id branchId FROM chat_channels WHERE id=@id AND is_active=1 AND is_test=1");const c=r.recordset[0];return c&&(req.user.role==='admin'||Number(c.branchId)===Number(b))?c:null}
async function messages(req,res,next){try{const p=await getPool(),c=await allowed(req,p,+req.params.id);if(!c)return fail(res,403,"Không có quyền xem kênh");const page=Math.max(1,+req.query.page||1),size=Math.min(50,Math.max(1,+req.query.pageSize||30)),r=await p.request().input("id",sql.Int,c.id).input("offset",sql.Int,(page-1)*size).input("size",sql.Int,size).query("SELECT m.id messageId,m.message_type messageType,m.content,m.reply_to_id replyToId,m.action_url actionUrl,m.created_at createdAt,u.full_name senderName FROM chat_messages m LEFT JOIN users u ON u.id=m.sender_user_id WHERE m.channel_id=@id AND m.is_deleted=0 ORDER BY m.id DESC OFFSET @offset ROWS FETCH NEXT @size ROWS ONLY");res.json({success:true,data:r.recordset.reverse(),pagination:{page,pageSize:size}})}catch(e){next(e)}}
async function send(req,res,next){try{const text=String(req.body.content||'').trim();if(!text||text.length>2000)return fail(res,400,"Nội dung không hợp lệ");const p=await getPool(),c=await allowed(req,p,+req.params.id);if(!c)return fail(res,403,"Không có quyền gửi vào kênh");let reply=req.body.replyToId?Number(req.body.replyToId):null;if(reply){const x=await p.request().input("id",sql.BigInt,reply).input("channel",sql.Int,c.id).query("SELECT id FROM chat_messages WHERE id=@id AND channel_id=@channel AND is_deleted=0");if(!x.recordset[0])return fail(res,400,"Tin nhắn trả lời không hợp lệ")}const r=await p.request().input("channel",sql.Int,c.id).input("uid",sql.Int,req.user.userId).input("reply",sql.BigInt,reply).input("text",sql.NVarChar(2000),text).query("INSERT chat_messages(channel_id,sender_user_id,reply_to_id,message_type,content,is_test) OUTPUT INSERTED.id messageId VALUES(@channel,@uid,@reply,'user',@text,1)");res.status(201).json({success:true,message:"Đã gửi",data:r.recordset[0]})}catch(e){next(e)}}
async function read(req,res,next){try{const p=await getPool(),c=await allowed(req,p,+req.params.id);if(!c)return fail(res,403,"Không có quyền");const last=await p.request().input("id",sql.Int,c.id).query("SELECT MAX(id) id FROM chat_messages WHERE channel_id=@id AND is_deleted=0");await p.request().input("channel",sql.Int,c.id).input("uid",sql.Int,req.user.userId).input("last",sql.BigInt,last.recordset[0].id).query("MERGE chat_read_states t USING(SELECT @channel channel_id,@uid user_id)s ON t.channel_id=s.channel_id AND t.user_id=s.user_id WHEN MATCHED THEN UPDATE SET last_read_message_id=@last,read_at=SYSDATETIME() WHEN NOT MATCHED THEN INSERT(channel_id,user_id,last_read_message_id) VALUES(@channel,@uid,@last);");res.json({success:true})}catch(e){next(e)}}
async function remove(req,res,next){try{const p=await getPool(),r=await p.request().input("id",sql.BigInt,req.params.id).input("uid",sql.Int,req.user.userId).query(`UPDATE chat_messages SET is_deleted=1,deleted_by=@uid,deleted_at=SYSDATETIME() WHERE id=@id AND is_test=1 AND (sender_user_id=@uid OR ${req.user.role==='admin'?1:0}=1);SELECT @@ROWCOUNT n`);if(!Number(r.recordset[0].n))return fail(res,403,"Không thể xóa tin nhắn");res.json({success:true})}catch(e){next(e)}}
module.exports={channels,messages,send,read,remove};
