const {sql,getPool}=require("../config/db");
const {businessNow,setBusinessNow}=require("../services/businessClockService");
const {record}=require("../services/shiftEventService");
const fail=(res,status,message)=>res.status(status).json({success:false,message});
const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v||""));
const validOperation=v=>["morning","evening"].includes(v);
const executor=tx=>({request:()=>new sql.Request(tx)});
async function scopeBranch(pool,user){if(user.role==="admin")return null;const r=await pool.request().input("uid",sql.Int,user.userId).query("SELECT TOP 1 branch_id AS branchId FROM employees WHERE user_id=@uid AND status='working'");return r.recordset[0]?.branchId||-1}

async function mappings(req,res,next){try{const pool=await getPool(),scope=await scopeBranch(pool,req.user),request=pool.request();if(scope>0)request.input("branchId",sql.Int,scope);const r=await request.query(`SELECT b.id AS branchId,b.branch_name AS branchName,s.id AS shiftId,s.shift_code AS shiftCode,s.shift_name AS shiftName,CONVERT(char(5),s.start_time,108) AS startTime,CONVERT(char(5),s.end_time,108) AS endTime,m.operation_shift_code AS operationShift,m.is_active AS isActive FROM branches b CROSS JOIN shifts s LEFT JOIN operation_shift_mappings m ON m.branch_id=b.id AND m.shift_id=s.id WHERE b.status='active' AND s.status='active'${scope>0?" AND b.id=@branchId":""} ORDER BY b.branch_name,s.start_time`);res.json({success:true,data:r.recordset})}catch(e){next(e)}}
async function saveMapping(req,res,next){try{const pool=await getPool(),branchId=Number(req.body.branchId),shiftId=Number(req.body.shiftId),operation=String(req.body.operationShift||""),scope=await scopeBranch(pool,req.user);if(!Number.isInteger(branchId)||!Number.isInteger(shiftId)||!validOperation(operation)||scope>0&&scope!==branchId)return fail(res,400,"Cấu hình mapping không hợp lệ");await pool.request().input("branchId",sql.Int,branchId).input("shiftId",sql.Int,shiftId).input("operation",sql.VarChar(10),operation).input("uid",sql.Int,req.user.userId).query(`MERGE operation_shift_mappings t USING(SELECT @branchId branch_id,@shiftId shift_id) s ON t.branch_id=s.branch_id AND t.shift_id=s.shift_id WHEN MATCHED THEN UPDATE SET operation_shift_code=@operation,is_active=1,updated_at=SYSDATETIME() WHEN NOT MATCHED THEN INSERT(branch_id,shift_id,operation_shift_code,created_by) VALUES(@branchId,@shiftId,@operation,@uid);`);res.json({success:true,message:"Đã lưu mapping ca vận hành"})}catch(e){next(e)}}

async function assignments(req,res,next){try{const pool=await getPool(),scope=await scopeBranch(pool,req.user),clock=await businessNow(pool),date=validDate(req.query.date)?req.query.date:clock.businessDate,branchId=scope>0?scope:Number(req.query.branchId||0),request=pool.request().input("date",sql.Date,date);if(branchId)request.input("branchId",sql.Int,branchId);const r=await request.query(`SELECT a.id AS assignmentId,a.branch_id AS branchId,b.branch_name AS branchName,CONVERT(char(10),a.business_date,23) AS businessDate,a.operation_shift_code AS operationShift,a.employee_id AS employeeId,u.full_name AS employeeName,e.employee_code AS employeeCode,a.assignment_role AS assignmentRole,a.note FROM operation_shift_assignments a JOIN employees e ON e.id=a.employee_id JOIN users u ON u.id=e.user_id JOIN branches b ON b.id=a.branch_id WHERE a.business_date=@date AND a.status='assigned' AND a.is_test=1${branchId?" AND a.branch_id=@branchId":""} ORDER BY b.branch_name,a.operation_shift_code; SELECT e.id AS employeeId,e.branch_id AS branchId,u.full_name AS employeeName,e.employee_code AS employeeCode,p.position_name AS positionName FROM employees e JOIN users u ON u.id=e.user_id JOIN positions p ON p.id=e.position_id WHERE e.status='working' AND u.status='active' AND e.is_test=1${branchId?" AND e.branch_id=@branchId":""} ORDER BY u.full_name; SELECT id AS branchId,branch_name AS branchName FROM branches WHERE status='active'${branchId?" AND id=@branchId":""} ORDER BY branch_name;`);res.json({success:true,data:{businessDate:date,items:r.recordsets[0],employees:r.recordsets[1],branches:r.recordsets[2]}})}catch(e){next(e)}}

async function assign(req,res,next){const pool=await getPool(),tx=new sql.Transaction(pool);let started=false;try{const branchId=Number(req.body.branchId),employeeId=Number(req.body.employeeId),date=req.body.businessDate,operation=String(req.body.operationShift||""),role=String(req.body.assignmentRole||"leader"),scope=await scopeBranch(pool,req.user);if(!Number.isInteger(branchId)||!Number.isInteger(employeeId)||!validDate(date)||!validOperation(operation)||!["leader","manager"].includes(role)||scope>0&&scope!==branchId)return fail(res,400,"Phân công không hợp lệ");await tx.begin();started=true;const ex=executor(tx);const eligible=await ex.request().input("branchId",sql.Int,branchId).input("employeeId",sql.Int,employeeId).input("date",sql.Date,date).input("operation",sql.VarChar(10),operation).query(`SELECT TOP 1 es.id FROM employee_schedules es JOIN operation_shift_mappings m ON m.branch_id=es.branch_id AND m.shift_id=es.shift_id AND m.is_active=1 WHERE es.employee_id=@employeeId AND es.branch_id=@branchId AND es.work_date=@date AND es.status<>'cancelled' AND es.is_test=1 AND m.operation_shift_code=@operation AND EXISTS(SELECT 1 FROM schedule_registration_periods rp WHERE rp.branch_id=es.branch_id AND rp.status='published' AND rp.is_test=1 AND es.work_date BETWEEN rp.week_start_date AND rp.week_end_date)`);if(!eligible.recordset[0]){await tx.rollback();started=false;return fail(res,409,"Nhân viên không có lịch chính thức đúng ca vận hành")};await ex.request().input("branchId",sql.Int,branchId).input("date",sql.Date,date).input("operation",sql.VarChar(10),operation).query("UPDATE operation_shift_assignments SET status='replaced',updated_at=SYSDATETIME() WHERE branch_id=@branchId AND business_date=@date AND operation_shift_code=@operation AND status='assigned'");const r=await ex.request().input("branchId",sql.Int,branchId).input("employeeId",sql.Int,employeeId).input("date",sql.Date,date).input("operation",sql.VarChar(10),operation).input("role",sql.VarChar(10),role).input("uid",sql.Int,req.user.userId).input("note",sql.NVarChar(500),String(req.body.note||"").trim()||null).query("INSERT operation_shift_assignments(branch_id,business_date,operation_shift_code,employee_id,assignment_role,assigned_by,note,is_test) OUTPUT INSERTED.id AS assignmentId VALUES(@branchId,@date,@operation,@employeeId,@role,@uid,@note,1)");await tx.commit();started=false;res.status(201).json({success:true,message:"Phân công người phụ trách thành công",data:r.recordset[0]})}catch(e){if(started)await tx.rollback().catch(()=>{});next(e)}}

async function overview(req,res,next){try{const pool=await getPool(),scope=await scopeBranch(pool,req.user),clock=await businessNow(pool),date=validDate(req.query.date)?req.query.date:clock.businessDate,branchId=scope>0?scope:Number(req.query.branchId||0),request=pool.request().input("date",sql.Date,date);if(branchId)request.input("branchId",sql.Int,branchId);const r=await request.query(`SELECT b.id AS branchId,b.branch_name AS branchName,o.operationShift,a.employee_id AS leaderEmployeeId,u.full_name AS leaderName,a.assignment_role AS assignmentRole,ss.id AS shiftSessionId,ss.status,ss.opened_at AS openedAt,ss.opening_cash AS openingCash FROM branches b CROSS APPLY(VALUES('morning'),('evening'))o(operationShift) LEFT JOIN operation_shift_assignments a ON a.branch_id=b.id AND a.business_date=@date AND a.operation_shift_code=o.operationShift AND a.status='assigned' AND a.is_test=1 LEFT JOIN employees e ON e.id=a.employee_id LEFT JOIN users u ON u.id=e.user_id LEFT JOIN shift_sessions ss ON ss.branch_id=b.id AND ss.business_date=@date AND ss.operation_shift_code=o.operationShift AND ss.status NOT IN('cancelled','CANCELLED') WHERE b.status='active'${branchId?" AND b.id=@branchId":""} ORDER BY b.branch_name,o.operationShift`);res.json({success:true,data:{businessDate:date,items:r.recordset}})}catch(e){next(e)}}

async function unlock(req,res,next){const pool=await getPool(),tx=new sql.Transaction(pool);let started=false;try{const reason=String(req.body.reason||"").trim();if(reason.length<5)return fail(res,400,"Lý do mở khóa tối thiểu 5 ký tự");await tx.begin();started=true;const ex=executor(tx),branch=await scopeBranch(ex,req.user),request=ex.request().input("id",sql.Int,req.params.id);if(branch>0)request.input("branch",sql.Int,branch);const r=await request.query(`SELECT TOP 1 id,branch_id AS branchId,leader_employee_id AS employeeId,status FROM shift_sessions WITH(UPDLOCK) WHERE id=@id AND is_test=1${branch>0?" AND branch_id=@branch":""}`),item=r.recordset[0];if(!item){await tx.rollback();started=false;return fail(res,404,"Không tìm thấy ca Sandbox hoặc ngoài phạm vi chi nhánh")};if(item.status!=="LOCKED"){await tx.rollback();started=false;return fail(res,409,"Chỉ ca đã khóa mới được mở khóa")};await ex.request().input("id",sql.Int,item.id).input("uid",sql.Int,req.user.userId).input("reason",sql.NVarChar(500),reason).query("UPDATE shift_sessions SET status='REOPENED',unlocked_at=SYSDATETIME(),unlocked_by=@uid,unlock_reason=@reason,updated_at=SYSDATETIME() WHERE id=@id");await record(ex,{sessionId:item.id,branchId:item.branchId,userId:req.user.userId,employeeId:item.employeeId,action:"SHIFT_UNLOCKED",oldStatus:"LOCKED",newStatus:"REOPENED",reason,payload:{reason}});await tx.commit();started=false;res.json({success:true,message:"Đã mở khóa ca"})}catch(e){if(started)await tx.rollback().catch(()=>{});next(e)}}
async function clock(req,res,next){try{const pool=await getPool();res.json({success:true,data:await businessNow(pool)})}catch(e){next(e)}}
async function updateClock(req,res,next){try{if(req.user.role!=="admin")return fail(res,403,"Chỉ Admin được đổi BusinessClock");const pool=await getPool();res.json({success:true,message:"Đã cập nhật ngày giờ nghiệp vụ",data:await setBusinessNow(pool,req.body.businessDateTime,req.user.userId)})}catch(e){if(e.status)return fail(res,e.status,e.message);next(e)}}
module.exports={mappings,saveMapping,assignments,assign,overview,unlock,clock,updateClock};
