const { sql, getPool } = require("../config/db");
const productTypes=["sale_item","ingredient","packaging"];
const productStatuses=["active","inactive","out_of_stock"];

async function getProducts(req,res,next){try{const pool=await getPool(),request=pool.request();let where="WHERE 1=1";if(req.query.status){request.input("status",sql.VarChar(20),req.query.status);where+=" AND p.status=@status"}if(req.query.type){request.input("type",sql.VarChar(30),req.query.type);where+=" AND p.product_type=@type"}const result=await request.query(`SELECT p.id,p.product_code AS productCode,p.product_name AS productName,p.product_type AS productType,p.sale_price AS salePrice,p.cost_price AS costPrice,p.minimum_stock AS minimumStock,p.image_url AS imageUrl,p.description,p.status,p.created_at AS createdAt,p.updated_at AS updatedAt,c.id AS categoryId,c.category_name AS categoryName,u.id AS unitId,u.unit_name AS unitName FROM products p INNER JOIN categories c ON c.id=p.category_id INNER JOIN units u ON u.id=p.unit_id ${where} ORDER BY p.product_name`);return res.json({success:true,data:result.recordset})}catch(error){return next(error)}}

function validate(body){if(!body.productCode||!body.productName||!Number.isInteger(Number(body.categoryId))||!Number.isInteger(Number(body.unitId)))return "Thiếu thông tin sản phẩm bắt buộc";if(!productTypes.includes(body.productType))return "Loại sản phẩm không hợp lệ";if(body.status&&!productStatuses.includes(body.status))return "Trạng thái không hợp lệ";if([body.salePrice,body.costPrice,body.minimumStock].some(value=>Number(value||0)<0))return "Giá và tồn kho tối thiểu không được âm";return null}

async function createProduct(req,res,next){try{const error=validate(req.body);if(error)return res.status(400).json({success:false,message:error});const b=req.body,pool=await getPool();const result=await pool.request().input("categoryId",sql.Int,Number(b.categoryId)).input("unitId",sql.Int,Number(b.unitId)).input("code",sql.VarChar(50),b.productCode.trim()).input("name",sql.NVarChar(200),b.productName.trim()).input("type",sql.VarChar(30),b.productType).input("sale",sql.Decimal(18,2),Number(b.salePrice||0)).input("cost",sql.Decimal(18,2),Number(b.costPrice||0)).input("minimum",sql.Decimal(18,3),Number(b.minimumStock||0)).input("image",sql.NVarChar(500),b.imageUrl||null).input("description",sql.NVarChar(1000),b.description||null).input("status",sql.VarChar(20),b.status||"active").query(`INSERT INTO products(category_id,unit_id,product_code,product_name,product_type,sale_price,cost_price,minimum_stock,image_url,description,status) OUTPUT INSERTED.id VALUES(@categoryId,@unitId,@code,@name,@type,@sale,@cost,@minimum,@image,@description,@status)`);return res.status(201).json({success:true,message:"Tạo sản phẩm thành công",data:{id:result.recordset[0].id}})}catch(error){return next(error)}}

async function updateProduct(req,res,next){try{const id=Number(req.params.id),error=validate(req.body);if(!Number.isInteger(id)||error)return res.status(400).json({success:false,message:error||"ID không hợp lệ"});const b=req.body,pool=await getPool();const result=await pool.request().input("id",sql.Int,id).input("categoryId",sql.Int,Number(b.categoryId)).input("unitId",sql.Int,Number(b.unitId)).input("code",sql.VarChar(50),b.productCode.trim()).input("name",sql.NVarChar(200),b.productName.trim()).input("type",sql.VarChar(30),b.productType).input("sale",sql.Decimal(18,2),Number(b.salePrice||0)).input("cost",sql.Decimal(18,2),Number(b.costPrice||0)).input("minimum",sql.Decimal(18,3),Number(b.minimumStock||0)).input("image",sql.NVarChar(500),b.imageUrl||null).input("description",sql.NVarChar(1000),b.description||null).input("status",sql.VarChar(20),b.status||"active").query(`UPDATE products SET category_id=@categoryId,unit_id=@unitId,product_code=@code,product_name=@name,product_type=@type,sale_price=@sale,cost_price=@cost,minimum_stock=@minimum,image_url=@image,description=@description,status=@status,updated_at=SYSDATETIME() WHERE id=@id; SELECT @@ROWCOUNT AS affected`);if(!result.recordset[0].affected)return res.status(404).json({success:false,message:"Không tìm thấy sản phẩm"});return res.json({success:true,message:"Cập nhật sản phẩm thành công"})}catch(error){return next(error)}}

async function deleteProduct(req,res,next){try{const id=Number(req.params.id);if(!Number.isInteger(id))return res.status(400).json({success:false,message:"ID không hợp lệ"});const pool=await getPool(),result=await pool.request().input("id",sql.Int,id).query("UPDATE products SET status='inactive',updated_at=SYSDATETIME() WHERE id=@id AND status<>'inactive'; SELECT @@ROWCOUNT AS affected");if(!result.recordset[0].affected)return res.status(404).json({success:false,message:"Không tìm thấy sản phẩm đang hoạt động"});return res.json({success:true,message:"Sản phẩm đã được ngừng sử dụng"})}catch(error){return next(error)}}

module.exports={getProducts,createProduct,updateProduct,deleteProduct};
