const router=require("express").Router();
const authenticate=require("../middleware/authMiddleware");
const allowRoles=require("../middleware/roleMiddleware");
const c=require("../controllers/employeeOperationsController");
const registration=require("../controllers/scheduleRegistrationController");
const payroll=require("../controllers/payrollController");
const oneShiftPerDay=(req,res,next)=>{const list=Array.isArray(req.body.registrations)?req.body.registrations:[],dates=list.map(x=>x.workDate);if(new Set(dates).size!==dates.length)return res.status(400).json({success:false,message:"Mỗi ngày chỉ được đăng ký tối đa một ca"});next()};
// Managers/admins may also have an employee profile and must clock in/out for
// their own published schedule. Controllers still resolve employee_id from JWT.
router.use(authenticate,allowRoles("employee","manager","admin"));
router.get("/payroll",payroll.mine);
router.get("/schedules",c.mySchedules);
router.get("/schedules/me",c.mySchedules);
router.get("/attendance",c.myAttendance);
router.get("/attendance/today",c.attendanceToday);
if(process.env.APP_ENV==="sandbox")router.get("/attendance/test-schedules",c.attendanceTestSchedules);
router.post("/attendance/check-in",c.attendanceCheckIn);
router.post("/attendance/check-out",c.attendanceCheckOut);
router.get("/attendance/history",c.attendanceHistory);
router.get("/shift-session",c.currentShiftSession);
router.post("/shift-session/open",c.openShiftSession);
router.post("/shift-session/close",c.closeShiftSession);
router.get("/shift-reports",c.myShiftReports);
router.get("/expenses",c.myExpenses);
router.post("/expenses",c.createExpense);
router.get("/leave-requests",c.myLeaveRequests);
router.post("/leave-requests",c.createLeaveRequest);
router.get("/notifications",c.myNotifications);
router.put("/notifications/:id/read",c.readNotification);
router.get("/shift-registration/current",registration.current);
router.get("/shift-registration",registration.current);
router.post("/shift-registration",oneShiftPerDay,registration.saveEmployeeCurrent);
router.put("/shift-registration/:periodId",oneShiftPerDay,registration.saveEmployee);
module.exports=router;
