const router=require("express").Router();
const authenticate=require("../middleware/authMiddleware");
const allowRoles=require("../middleware/roleMiddleware");
const controller=require("../controllers/importController");
const upload=require("../middleware/operationUpload");
router.use(authenticate);
router.get("/employee/options",allowRoles("employee"),controller.employeeOptions);
router.post("/employee",allowRoles("employee"),controller.employeeCreate);
router.post("/employee/:id/document",allowRoles("employee"),upload.single("image"),controller.employeeDocument);
router.use(allowRoles("admin","manager"));
router.get("/",controller.list);
router.get("/:id/documents/:documentId",controller.documentFile);
router.get("/:id",controller.detail);
router.post("/",controller.create);
router.put("/:id",controller.update);
router.delete("/:id",controller.remove);
router.post("/:id/confirm",controller.confirm);
router.post("/:id/adjustments",controller.adjust);
module.exports=router;
