const router=require("express").Router();
const authenticate=require("../middleware/authMiddleware");
const allowRoles=require("../middleware/roleMiddleware");
const controller=require("../controllers/purchaseOrderController");
router.use(authenticate,allowRoles("admin","manager"));
router.get("/",controller.list);
router.get("/:id/export.xlsx",controller.excel);
router.get("/:id/export.pdf",controller.pdf);
router.get("/:id",controller.detail);
router.post("/",controller.create);
router.put("/:id",controller.update);
router.delete("/:id",controller.remove);
module.exports=router;
