const router=require('express').Router();
const authenticate=require('../middleware/authMiddleware');
const allowRoles=require('../middleware/roleMiddleware');
const upload=require('../middleware/operationUpload');
const c=require('../controllers/shiftInventoryController');
router.use(authenticate,allowRoles('admin','manager','employee'));
router.get('/current',c.current);router.post('/current/start',c.start);
router.get('/admin/options',allowRoles('admin','manager'),c.options);
router.post('/admin/baseline',allowRoles('admin','manager'),c.baseline);
router.get('/admin/sessions',allowRoles('admin','manager'),c.sessions);
router.get('/admin/discrepancies',allowRoles('admin','manager'),c.discrepancies);
router.post('/admin/discrepancies/:id/resolve',allowRoles('admin','manager'),c.resolve);
router.get('/images/:attachmentId/file',c.image);
router.get('/:id/movements',c.movements);
router.post('/:id/usage',c.recordUsage);
router.post('/:id/images',upload.single('image'),c.uploadImage);
router.post('/:id/receive',c.receive);
router.post('/:id/close',c.close);
router.get('/:id',c.detail);
module.exports=router;
