const path=require("path");
const ExcelJS=require("exceljs");
process.env.APP_ENV="production";
const {sql,getPool}=require("../config/db");

const filePath=path.resolve(__dirname,"../../database/kho-import.xlsx");
const apply=process.argv.includes("--apply");
const sourceNote="Nhập từ kho.xlsx ngày 05/09/2026";
const branchCodes={VK:"CN001",VV:"GVV",GV:"GGV"};
const supplierDefs={
 SENVIET:{code:"NCC-SENVIET",name:"Sen Việt",group:"Nguyên liệu"},
 PACKAGING:{code:"NCC-BAOBI",name:"Nhà cung cấp bao bì & dụng cụ",group:"Bao bì và dụng cụ"},
 CHICKEN:{code:"NCC-GATUOI",name:"Nhà cung cấp thịt gà",group:"Thịt gà"},
 TOK:{code:"NCC-TOK",name:"Nhà cung cấp TOK",group:"TOK"},
};

function value(cell){const raw=cell?.value;if(raw==null)return"";if(typeof raw!=="object")return String(raw).trim();return String(raw.text??raw.result??(raw.richText?raw.richText.map(x=>x.text).join(""):"")).trim()}
function number(cell){const raw=value(cell).replace(/\./g,"").replace(",",".").replace(/[^0-9.-]/g,"");const parsed=Number(raw);return Number.isFinite(parsed)&&parsed>0?parsed:0}
function slug(input){return String(input).normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/gi,"d").toUpperCase().replace(/[^A-Z0-9]+/g,"_").replace(/^_|_$/g,"").slice(0,38)}
function generatedCode(name){return `IMP_${slug(name)||"SANPHAM"}`}
function unitCode(name){const normalized=slug(name);return normalized==="TUI"?"BAG":normalized==="CAI"?"PIECE":normalized==="THUNG"?"BOX":normalized==="CHAI"?"BOTTLE":normalized==="CAN"?"CAN":normalized==="BO"?"SET":normalized==="KG"?"KG":normalized||"UNIT"}
function inferUnit(description,name){const raw=`${description} ${name}`.toLowerCase();if(raw.includes("cái/thùng")||raw.includes("ly ")||raw.includes("nắp ")||raw.includes("tô "))return"CÁI";if(raw.includes("túi")||raw.includes("kg"))return"TÚI";if(raw.includes("chai"))return"CHAI";if(raw.includes("bộ"))return"BỘ";return"ĐƠN VỊ"}

async function parse(){
 const workbook=new ExcelJS.Workbook();await workbook.xlsx.readFile(filePath);const sheet=workbook.worksheets[0];
 const catalog=new Map();
 for(let row=3;row<=24;row++){const name=value(sheet.getCell(row,3));if(!name)continue;const code=value(sheet.getCell(row,2))||generatedCode(name),description=value(sheet.getCell(row,4));catalog.set(slug(name),{code,name,description,unit:inferUnit(description,name),type:/ly |nắp |tô |chai nhựa/i.test(name)?"packaging":"ingredient"})}
 for(let row=26;row<=44;row++){const name=value(sheet.getCell(row,2));if(!name)continue;const description=value(sheet.getCell(row,6));if(!catalog.has(slug(name)))catalog.set(slug(name),{code:generatedCode(name),name,description,unit:inferUnit(description,name),type:"ingredient"})}
 const receipts=[];
 const addReceipt=(branch,supplier,date,items,label)=>{const grouped=new Map();for(const item of items){if(!item.name||!item.quantity)continue;const key=slug(item.name),known=catalog.get(key),description=known?.description||"",boxMatch=description.match(/(\d[\d.]*)\s*cái\s*\/\s*thùng/i);let quantity=item.quantity,unit=item.unit||known?.unit||"ĐƠN VỊ";if(slug(unit)==="THUNG"&&boxMatch){quantity*=Number(boxMatch[1].replace(".",""));unit="CÁI"}const product=known||{code:generatedCode(item.name),name:item.name,description:"Tạo từ đơn đặt hàng trong kho.xlsx",unit,type:supplier==="PACKAGING"?"packaging":"ingredient"};catalog.set(key,{...product,unit:known?.unit||unit});const current=grouped.get(key);if(current)current.quantity+=quantity;else grouped.set(key,{productKey:key,quantity,orderedUnit:item.unit||unit})}if(grouped.size)receipts.push({branch,supplier,date,label,items:[...grouped.values()]})};
 const columns=[{branch:"VK",name:9,unit:10,qty:11},{branch:"VV",name:14,unit:15,qty:16},{branch:"GV",name:19,unit:20,qty:21}];
 for(const col of columns){const items=[];for(let row=3;row<=25;row++)items.push({name:value(sheet.getCell(row,col.name)),unit:value(sheet.getCell(row,col.unit)),quantity:number(sheet.getCell(row,col.qty))});addReceipt(col.branch,"SENVIET","2026-09-07",items,"Đơn NVL 07/09-13/09")}
 const packaging=[];for(let row=32;row<=52;row++)packaging.push({name:value(sheet.getCell(row,19)),unit:value(sheet.getCell(row,20)),quantity:number(sheet.getCell(row,21))});addReceipt("GV","PACKAGING","2026-09-07",packaging,"Đơn bao bì dụng cụ")
 const special=(branch,supplier,date,quantity,name,unit)=>addReceipt(branch,supplier,date,[{name,unit,quantity}],supplier==="CHICKEN"?"Lịch đặt gà":"Lịch đặt TOK");
 special("VK","CHICKEN","2026-09-07",120,"Má đùi gà làm sạch rút xương đã tẩm ướp","KG");special("VV","CHICKEN","2026-09-07",100,"Má đùi gà làm sạch rút xương đã tẩm ướp","KG");special("GV","CHICKEN","2026-08-27",100,"Má đùi gà làm sạch rút xương đã tẩm ướp","KG");
 special("VK","TOK","2026-09-07",60,"Thịt gà TOK","KG");special("VV","TOK","2026-09-07",60,"Thịt gà TOK","KG");special("GV","TOK","2026-08-27",40,"Thịt gà TOK","KG");
 return {catalog,receipts};
}

async function main(){
 const {catalog,receipts}=await parse(),pool=await getPool();
 const before=await pool.request().query("SELECT COUNT(*) suppliers FROM suppliers;SELECT COUNT(*) products FROM products;SELECT COUNT(*) completedReceipts FROM purchase_receipts WHERE status='completed';SELECT COUNT(*) inventories FROM branch_inventories;");
 const summary={productsInFile:catalog.size,receipts:receipts.map(r=>({branch:r.branch,supplier:r.supplier,date:r.date,lines:r.items.length,quantity:r.items.reduce((sum,x)=>sum+x.quantity,0)})),before:Object.assign({},...before.recordsets.map(rows=>rows[0]))};
 if(!apply){console.log(JSON.stringify(summary,null,2));await pool.close();return}
 const tx=new sql.Transaction(pool);let begun=false;
 try{
  await tx.begin();begun=true;
  const admin=(await new sql.Request(tx).query("SELECT TOP 1 u.id FROM users u JOIN roles r ON r.id=u.role_id WHERE r.role_code='admin' AND u.status='active' ORDER BY u.id")).recordset[0];if(!admin)throw new Error("Không tìm thấy admin đang hoạt động");
  const categories={};for(const item of [{code:"INGREDIENT",name:"Nguyên liệu",type:"ingredient"},{code:"PACKAGING",name:"Bao bì & dụng cụ",type:"packaging"}]){await new sql.Request(tx).input("code",sql.VarChar(30),item.code).input("name",sql.NVarChar(150),item.name).input("type",sql.VarChar(30),item.type).query("IF NOT EXISTS(SELECT 1 FROM categories WHERE category_code=@code) INSERT categories(category_code,category_name,category_type,status) VALUES(@code,@name,@type,'active')");categories[item.type]=(await new sql.Request(tx).input("code",sql.VarChar(30),item.code).query("SELECT id FROM categories WHERE category_code=@code")).recordset[0].id}
  const suppliers={};for(const [key,item] of Object.entries(supplierDefs)){await new sql.Request(tx).input("code",sql.VarChar(30),item.code).input("name",sql.NVarChar(200),item.name).query("IF NOT EXISTS(SELECT 1 FROM suppliers WHERE supplier_code=@code) INSERT suppliers(supplier_code,supplier_name,status) VALUES(@code,@name,'active')");suppliers[key]=(await new sql.Request(tx).input("code",sql.VarChar(30),item.code).query("SELECT id FROM suppliers WHERE supplier_code=@code")).recordset[0].id}
  const productIds=new Map();for(const [key,item] of catalog){const uCode=unitCode(item.unit),uName=item.unit||"Đơn vị";await new sql.Request(tx).input("code",sql.VarChar(30),uCode).input("name",sql.NVarChar(100),uName).query("IF NOT EXISTS(SELECT 1 FROM units WHERE unit_code=@code) INSERT units(unit_code,unit_name) VALUES(@code,@name)");const unit=(await new sql.Request(tx).input("code",sql.VarChar(30),uCode).query("SELECT id FROM units WHERE unit_code=@code")).recordset[0];let code=item.code.slice(0,50);const collision=(await new sql.Request(tx).input("code",sql.VarChar(50),code).input("name",sql.NVarChar(200),item.name).query("SELECT product_name FROM products WHERE product_code=@code AND product_name<>@name")).recordset[0];if(collision)code=`${code.slice(0,42)}_${slug(item.name).slice(-7)}`;await new sql.Request(tx).input("category",sql.Int,categories[item.type]).input("unit",sql.Int,unit.id).input("code",sql.VarChar(50),code).input("name",sql.NVarChar(200),item.name).input("type",sql.VarChar(30),item.type).input("description",sql.NVarChar(1000),item.description||sourceNote).query(`MERGE products target USING(SELECT @code product_code) source ON target.product_code=source.product_code WHEN MATCHED THEN UPDATE SET product_name=@name,category_id=@category,unit_id=@unit,product_type=@type,description=COALESCE(NULLIF(@description,''),target.description),status='active',updated_at=SYSDATETIME() WHEN NOT MATCHED THEN INSERT(category_id,unit_id,product_code,product_name,product_type,sale_price,cost_price,minimum_stock,description,status) VALUES(@category,@unit,@code,@name,@type,0,0,0,@description,'active');`);productIds.set(key,(await new sql.Request(tx).input("code",sql.VarChar(50),code).query("SELECT id FROM products WHERE product_code=@code")).recordset[0].id)}
  const branches=new Map((await new sql.Request(tx).query("SELECT id,branch_code FROM branches WHERE status='active'")).recordset.map(r=>[r.branch_code,r.id]));let createdReceipts=0;
  for(const receipt of receipts){const branchId=branches.get(branchCodes[receipt.branch]);if(!branchId)throw new Error(`Không tìm thấy chi nhánh ${receipt.branch}`);const code=`KHOXLSX-${receipt.date.replaceAll("-","")}-${receipt.branch}-${receipt.supplier}`;if((await new sql.Request(tx).input("code",sql.VarChar(50),code).query("SELECT id FROM purchase_receipts WHERE receipt_code=@code")).recordset[0])continue;const header=await new sql.Request(tx).input("code",sql.VarChar(50),code).input("branch",sql.Int,branchId).input("supplier",sql.Int,suppliers[receipt.supplier]).input("admin",sql.Int,admin.id).input("date",sql.DateTime2,`${receipt.date}T09:00:00`).input("note",sql.NVarChar(500),`${receipt.label}. ${sourceNote}`).query("INSERT purchase_receipts(receipt_code,branch_id,supplier_id,created_by,receipt_date,total_amount,status,note,confirmed_at,reviewed_at,reviewed_by) OUTPUT INSERTED.id VALUES(@code,@branch,@supplier,@admin,@date,0,'completed',@note,SYSDATETIME(),SYSDATETIME(),@admin)");const receiptId=header.recordset[0].id;for(const line of receipt.items){const productId=productIds.get(line.productKey);await new sql.Request(tx).input("receipt",sql.Int,receiptId).input("branch",sql.Int,branchId).input("product",sql.Int,productId).input("qty",sql.Decimal(18,3),line.quantity).query("INSERT purchase_receipt_items(purchase_receipt_id,product_id,quantity,unit_price) VALUES(@receipt,@product,@qty,0);MERGE branch_inventories target USING(SELECT @branch branch_id,@product product_id) source ON target.branch_id=source.branch_id AND target.product_id=source.product_id WHEN MATCHED THEN UPDATE SET quantity=target.quantity+@qty,updated_at=SYSDATETIME() WHEN NOT MATCHED THEN INSERT(branch_id,product_id,quantity,average_cost) VALUES(@branch,@product,@qty,0);");await new sql.Request(tx).input("branch",sql.Int,branchId).input("product",sql.Int,productId).input("qty",sql.Decimal(18,3),line.quantity).input("receipt",sql.Int,receiptId).input("admin",sql.Int,admin.id).input("reason",sql.NVarChar(500),sourceNote).query("INSERT inventory_transactions(branch_id,product_id,transaction_type,quantity,unit_cost,reference_type,reference_id,reason,created_by) VALUES(@branch,@product,'import',@qty,0,'purchase_receipt',@receipt,@reason,@admin)")}createdReceipts++}
  await tx.commit();begun=false;const after=await pool.request().query("SELECT COUNT(*) suppliers FROM suppliers;SELECT COUNT(*) products FROM products;SELECT COUNT(*) completedReceipts FROM purchase_receipts WHERE status='completed';SELECT COUNT(*) inventories FROM branch_inventories;SELECT COUNT(*) importedTransactions,SUM(quantity) importedQuantity FROM inventory_transactions WHERE reason=N'Nhập từ kho.xlsx ngày 05/09/2026';");console.log(JSON.stringify({...summary,applied:true,createdReceipts,after:Object.assign({},...after.recordsets.map(rows=>rows[0]))},null,2));
 }catch(error){if(begun)await tx.rollback().catch(()=>{});throw error}finally{await pool.close()}
}
main().catch(error=>{console.error(error);process.exit(1)});
