import { useEffect, useMemo, useState } from "react";
import { FiEdit2, FiPlus, FiSearch, FiTrash2, FiX } from "react-icons/fi";
import { categoryApi, productApi, unitApi } from "../../api/services";

const blank={productCode:"",productName:"",categoryId:"",unitId:"",productType:"ingredient",salePrice:0,costPrice:0,minimumStock:0,imageUrl:"",description:"",status:"active"};
const rows=value=>Array.isArray(value?.data)?value.data:Array.isArray(value?.data?.items)?value.data.items:Array.isArray(value?.items)?value.items:[];

function Editor({product,categories,units,onClose,onSaved}){
  const defaultCategory=categories.find(item=>item.status==="active")||categories[0];
  const defaultUnit=units.find(item=>item.status==="active")||units[0];
  const [form,setForm]=useState(product?{...blank,...product,categoryId:String(product.categoryId),unitId:String(product.unitId)}:{...blank,categoryId:String(defaultCategory?.categoryId||""),unitId:String(defaultUnit?.id||"")});
  const [saving,setSaving]=useState(false),[error,setError]=useState("");
  const change=event=>setForm(value=>({...value,[event.target.name]:event.target.value}));
  const submit=async event=>{event.preventDefault();if(!form.categoryId||!form.unitId){setError("Cần có ít nhất một danh mục và đơn vị tính đang hoạt động trước khi thêm nguyên liệu.");return}setSaving(true);setError("");try{const payload={...form,categoryId:Number(form.categoryId),unitId:Number(form.unitId),salePrice:Number(form.salePrice||0),costPrice:Number(form.costPrice||0),minimumStock:Number(form.minimumStock||0)};product?await productApi.update(product.id,payload):await productApi.create(payload);onSaved(product?"Đã cập nhật nguyên liệu.":"Đã thêm nguyên liệu.")}catch(err){setError(err.response?.data?.message||"Không thể lưu nguyên liệu.")}finally{setSaving(false)}};
  return <div className="manager-modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><form className="employee-modal product-editor-modal product-editor-compact" onSubmit={submit}>
    <header><div><h2>{product?"Chỉnh sửa nguyên liệu":"Thêm nguyên liệu"}</h2><p>Thông tin dùng trong sổ kho, nhập hàng và xuất hàng.</p></div><button type="button" onClick={onClose}><FiX/></button></header>
    <div className="product-editor-body">{error&&<div className="manager-form-error">{error}</div>}<div className="product-editor-grid">
      <label>Mã NVL *<input name="productCode" required maxLength="50" value={form.productCode} onChange={change}/></label>
      <label>Tên nguyên liệu *<input name="productName" required maxLength="200" value={form.productName} onChange={change}/></label>
      <label>Nhóm nguyên liệu *<select name="categoryId" required value={form.categoryId} onChange={change}><option value="">Chọn nhóm nguyên liệu</option>{categories.filter(item=>item.status==="active"||String(item.categoryId)===String(form.categoryId)).map(item=><option key={item.categoryId} value={item.categoryId}>{item.categoryName}</option>)}</select></label>
      <label className="product-description">Quy cách<textarea name="description" rows="3" maxLength="1000" placeholder="Ví dụ: 1,3kg/túi x 20 túi/thùng" value={form.description||""} onChange={change}/></label>
    </div></div><footer><button type="button" className="btn" onClick={onClose}>Hủy</button><button className="btn btn-primary" disabled={saving}>{saving?"Đang lưu...":"Lưu nguyên liệu"}</button></footer>
  </form></div>;
}

export default function ProductsPage({embedded=false}){
  const [products,setProducts]=useState([]),[categories,setCategories]=useState([]),[units,setUnits]=useState([]),[search,setSearch]=useState(""),[group,setGroup]=useState("all");
  const [loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[editing,setEditing]=useState(undefined),[deleting,setDeleting]=useState(null),[addingGroup,setAddingGroup]=useState(false),[groupName,setGroupName]=useState("");
  const load=async()=>{setLoading(true);setError("");try{const [productResult,categoryResult,unitResult]=await Promise.all([productApi.list(),categoryApi.list({limit:100}),unitApi.list({limit:100})]);setProducts(rows(productResult));setCategories(rows(categoryResult));setUnits(rows(unitResult).map(item=>({...item,id:item.id,unitName:item.unitName||item.unit_name||item.name})));}catch(err){setError(err.response?.data?.message||"Không tải được danh sách nguyên liệu.")}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>products.filter(item=>item.status==="active"&&(group==="all"||String(item.categoryId)===group)&&(!search||`${item.productName} ${item.productCode} ${item.description||""} ${item.categoryName||""}`.toLowerCase().includes(search.toLowerCase()))),[products,search,group]);
  const saved=message=>{setEditing(undefined);setNotice(message);load()};
  const remove=async()=>{try{await productApi.remove(deleting.id);setDeleting(null);setNotice("Đã xóa nguyên liệu khỏi danh sách sử dụng. Lịch sử kho vẫn được giữ nguyên.");load()}catch(err){setError(err.response?.data?.message||"Không thể xóa nguyên liệu.");setDeleting(null)}};
  const createGroup=async event=>{event.preventDefault();try{const result=await categoryApi.create({categoryName:groupName,status:"active",description:"Nhóm nguyên liệu"});setAddingGroup(false);setGroupName("");setNotice(result.message||"Đã thêm nhóm nguyên liệu.");await load();if(result.data?.categoryId)setGroup(String(result.data.categoryId))}catch(err){setError(err.response?.data?.message||"Không thể thêm nhóm nguyên liệu.")}};
  return <div className={`product-management-panel ${embedded?"embedded":"card"}`}><div className="product-management-head"><div><h3>Quản lý nguyên liệu</h3><p>Danh mục nguyên liệu sử dụng trong sổ và nghiệp vụ kho.</p></div><button className="btn btn-primary" onClick={()=>setEditing(null)}><FiPlus/> Thêm nguyên liệu</button></div>
    {notice&&<div className="manager-form-success">{notice}</div>}{error&&<div className="manager-form-error">{error}</div>}
    <div className="product-filters product-filters-compact"><div className="product-search"><FiSearch/><input placeholder="Tìm mã NVL, tên nguyên liệu hoặc quy cách" value={search} onChange={event=>setSearch(event.target.value)}/></div><div className="material-group-filter"><label>Nhóm nguyên liệu<select value={group} onChange={event=>setGroup(event.target.value)}><option value="all">Tất cả nhóm nguyên liệu</option>{categories.filter(item=>item.status==="active").map(item=><option key={item.categoryId} value={item.categoryId}>{item.categoryName} ({item.productCount||0})</option>)}</select></label><button className="btn btn-light" onClick={()=>setAddingGroup(true)}><FiPlus/> Thêm nhóm nguyên liệu khác</button></div></div>
    <div className="card product-table-card product-material-table"><div className="inventory-table-head"><h3>Danh sách nguyên liệu</h3><p>{filtered.length} nguyên liệu</p></div><div className="table-wrap"><table><thead><tr><th>STT</th><th>Mã NVL</th><th>Tên nguyên liệu</th><th>Nhóm</th><th>Quy cách</th><th>Thao tác</th></tr></thead><tbody>{!loading&&filtered.length?filtered.map((item,index)=><tr key={item.id}><td>{index+1}</td><td><b>{item.productCode}</b></td><td><b>{item.productName}</b></td><td><span className="material-group-badge">{item.categoryName}</span></td><td>{item.description||"—"}</td><td><div className="product-actions"><button title="Sửa" onClick={()=>setEditing(item)}><FiEdit2/></button><button className="danger" title="Xóa" onClick={()=>setDeleting(item)}><FiTrash2/></button></div></td></tr>):<tr><td colSpan="6" className="empty-cell">{loading?"Đang tải nguyên liệu...":"Không tìm thấy nguyên liệu."}</td></tr>}</tbody></table></div></div>
    {editing!==undefined&&<Editor product={editing} categories={categories} units={units} onClose={()=>setEditing(undefined)} onSaved={saved}/>} {addingGroup&&<div className="manager-modal-backdrop"><form className="employee-modal product-delete-modal material-group-modal" onSubmit={createGroup}><header><div><h2>Thêm nhóm nguyên liệu khác</h2><p>Ví dụ: Gà, Ly – nắp, Gia vị...</p></div><button type="button" onClick={()=>setAddingGroup(false)}><FiX/></button></header><div className="product-delete-body"><label>Tên nhóm *<input required autoFocus maxLength="150" value={groupName} onChange={event=>setGroupName(event.target.value)}/></label></div><footer><button type="button" className="btn" onClick={()=>setAddingGroup(false)}>Hủy</button><button className="btn btn-primary">Thêm nhóm</button></footer></form></div>} {deleting&&<div className="manager-modal-backdrop"><div className="employee-modal product-delete-modal"><header><div><h2>Xóa nguyên liệu?</h2><p>{deleting.productName}</p></div><button onClick={()=>setDeleting(null)}><FiX/></button></header><div className="product-delete-body">Nguyên liệu sẽ không còn xuất hiện trong kho và phiếu nhập–xuất mới. Toàn bộ số liệu và lịch sử cũ vẫn được giữ nguyên.</div><footer><button className="btn" onClick={()=>setDeleting(null)}>Hủy</button><button className="btn product-delete-confirm" onClick={remove}>Xóa nguyên liệu</button></footer></div></div>}
  </div>;
}
