import {useEffect,useMemo,useState} from "react";
import {FiArrowLeft,FiCheckCircle,FiClock,FiRefreshCw} from "react-icons/fi";
import {useNavigate} from "react-router-dom";
import {sandboxAttendanceApi} from "../../api/services";

const scenarioOptions=[
 ["on_time","Đúng giờ"],["late_5","Đi trễ 5 phút"],["late_15","Đi trễ 15 phút"],["late_30","Đi trễ 30 phút"],
 ["early_15","Về sớm 15 phút"],["early_30","Về sớm 30 phút"],["overtime_30","Tăng ca 30 phút"],["overtime_60","Tăng ca 60 phút"],
 ["missing_checkout","Quên chấm ra"],["absent","Nghỉ không phép"],["manual","Nhập giờ thủ công"]
];
const scenarioLabel=Object.fromEntries(scenarioOptions),pad=value=>String(value).padStart(2,"0");
const duration=value=>value==null?"—":`${Math.floor(Number(value)/60)} giờ ${Number(value)%60} phút`;
const add=(value,minutes)=>{const [date,time]=value.split("T"),[year,month,day]=date.split("-").map(Number),[hour,minute]=time.split(":").map(Number),result=new Date(Date.UTC(year,month-1,day,hour,minute)+minutes*60000);return `${result.getUTCFullYear()}-${pad(result.getUTCMonth()+1)}-${pad(result.getUTCDate())}T${pad(result.getUTCHours())}:${pad(result.getUTCMinutes())}`};
const preview=(row,choice)=>{let checkIn=`${row.workDate}T${row.startTime}`,checkOut=`${row.workDate}T${row.endTime}`;if(row.endTime<=row.startTime)checkOut=add(checkOut,1440);let late=0,early=0;
 if(choice.scenario.startsWith("late_")){late=Number(choice.scenario.split("_")[1]);checkIn=add(checkIn,late)}
 if(choice.scenario.startsWith("early_")){early=Number(choice.scenario.split("_")[1]);checkOut=add(checkOut,-early)}
 if(choice.scenario.startsWith("overtime_"))checkOut=add(checkOut,Number(choice.scenario.split("_")[1]));
 if(choice.scenario==="missing_checkout")checkOut="";if(choice.scenario==="absent"){checkIn="";checkOut=""}
 if(choice.scenario==="manual"){checkIn=choice.checkInTime||"";checkOut=choice.checkOutTime||""}
 const total=checkIn&&checkOut?Math.max(0,Math.round((new Date(`${checkOut}:00Z`)-new Date(`${checkIn}:00Z`))/60000)):choice.scenario==="absent"?0:null;
 return {checkIn,checkOut,total,late,early};};

export default function AttendanceTestPage(){
 const navigate=useNavigate(),[options,setOptions]=useState({branches:[],periods:[],employees:[]}),[filters,setFilters]=useState({branchId:"",periodId:"",employeeId:"",from:"",to:""}),[rows,setRows]=useState([]),[choices,setChoices]=useState({}),[conflictMode,setConflictMode]=useState("skip"),[error,setError]=useState(""),[success,setSuccess]=useState(""),[loading,setLoading]=useState(false);
 useEffect(()=>{sandboxAttendanceApi.options().then(({data})=>{setOptions(data);const period=data.periods[0];if(period)setFilters({branchId:String(period.branchId),periodId:String(period.periodId),employeeId:"",from:period.startDate,to:period.endDate})}).catch(e=>setError(e.response?.data?.message||"Không tải được cấu hình Sandbox"))},[]);
 const period=options.periods.find(item=>String(item.periodId)===String(filters.periodId));
 const employees=options.employees.filter(item=>!period||Number(item.branchId)===Number(period.branchId));
 const periods=options.periods.filter(item=>!filters.branchId||String(item.branchId)===String(filters.branchId));
 const load=async()=>{setLoading(true);setError("");setSuccess("");try{const response=await sandboxAttendanceApi.schedules(filters);setRows(response.data);setChoices(Object.fromEntries(response.data.map(row=>[row.scheduleId,{scenario:"on_time",checkInTime:`${row.workDate}T${row.startTime}`,checkOutTime:`${row.workDate}T${row.endTime}`}])))}catch(e){setError(e.response?.data?.message||"Không tải được lịch đã công bố")}finally{setLoading(false)}};
 useEffect(()=>{if(filters.periodId&&filters.from&&filters.to)load()},[filters.periodId,filters.employeeId,filters.from,filters.to]);
 const prepared=useMemo(()=>rows.map(row=>({...row,...preview(row,choices[row.scheduleId]||{scenario:"on_time"})})),[rows,choices]);
 const submit=async()=>{setLoading(true);setError("");setSuccess("");try{const payload=prepared.map(row=>({scheduleId:row.scheduleId,employeeId:row.employeeId,scenario:choices[row.scheduleId]?.scenario||"on_time",checkInTime:choices[row.scheduleId]?.checkInTime,checkOutTime:choices[row.scheduleId]?.checkOutTime}));const response=await sandboxAttendanceApi.generate({conflictMode,rows:payload});setSuccess(`${response.message}: tạo ${response.data.created}, cập nhật ${response.data.updated}, bỏ qua ${response.data.skipped}.`);await load()}catch(e){setError(e.response?.data?.message||"Không thể tạo dữ liệu chấm công test")}finally{setLoading(false)}};
 const choose=(id,patch)=>setChoices(old=>({...old,[id]:{...old[id],...patch}}));
 return <div className="attendance-test-page"><button className="btn btn-light attendance-test-back" onClick={()=>navigate("/manager/attendance")}><FiArrowLeft/> Quay lại chấm công</button>
  <header className="attendance-test-banner"><FiClock/><div><h1>CHỨC NĂNG TẠO DỮ LIỆU CHẤM CÔNG KIỂM THỬ</h1><p>Chỉ hoạt động trong Sandbox · Database _Test · Không phải dữ liệu thật</p></div></header>
  {error&&<div className="manager-form-error">{error}</div>}{success&&<div className="manager-form-success">{success}</div>}
  <section className="card attendance-test-controls"><label>Chi nhánh<select value={filters.branchId} onChange={e=>{const next=options.periods.find(x=>String(x.branchId)===e.target.value);setFilters({branchId:e.target.value,periodId:next?String(next.periodId):"",employeeId:"",from:next?.startDate||"",to:next?.endDate||""})}}>{options.branches.map(x=><option key={x.branchId} value={x.branchId}>{x.branchName}</option>)}</select></label><label>Đợt/tuần đã công bố<select value={filters.periodId} onChange={e=>{const selected=options.periods.find(x=>String(x.periodId)===e.target.value);setFilters({...filters,periodId:e.target.value,employeeId:"",from:selected?.startDate||"",to:selected?.endDate||""})}}>{periods.map(x=><option key={x.periodId} value={x.periodId}>{x.title} · {x.startDate}–{x.endDate}</option>)}</select></label><label>Nhân viên<select value={filters.employeeId} onChange={e=>setFilters({...filters,employeeId:e.target.value})}><option value="">Tất cả nhân viên</option>{employees.map(x=><option value={x.employeeId} key={x.employeeId}>{x.fullName} ({x.employeeCode})</option>)}</select></label><label>Từ ngày<input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>Đến ngày<input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><label>Xử lý dữ liệu trùng<select value={conflictMode} onChange={e=>setConflictMode(e.target.value)}><option value="skip">Bỏ qua</option><option value="update">Cập nhật</option><option value="replace">Xóa test và tạo lại</option></select></label><button className="btn btn-light" onClick={load}><FiRefreshCw/> Tải lại</button></section>
  <section className="card attendance-test-preview"><div className="section-title"><div><h2>Bảng xem trước</h2><p>{prepared.length} lịch chính thức có thể tạo chấm công</p></div><button className="btn btn-yellow" disabled={loading||!prepared.length} onClick={submit}><FiCheckCircle/>{loading?"Đang xử lý...":"Tạo dữ liệu kiểm thử"}</button></div>
   <div className="table-wrap"><table><thead><tr><th>Ngày</th><th>Nhân viên</th><th>Ca</th><th>Kịch bản</th><th>Giờ vào</th><th>Giờ ra</th><th>Tổng giờ</th><th>Trễ</th><th>Về sớm</th><th>Dữ liệu cũ</th></tr></thead><tbody>{prepared.map(row=>{const choice=choices[row.scheduleId]||{scenario:"on_time"};return <tr key={row.scheduleId}><td>{row.workDate}</td><td><b>{row.fullName}</b><small>{row.employeeCode}</small></td><td><b>{row.shiftCode}</b><small>{row.startTime}–{row.endTime}</small></td><td><select value={choice.scenario} onChange={e=>choose(row.scheduleId,{scenario:e.target.value})}>{scenarioOptions.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>{choice.scenario==="manual"&&<span className="attendance-test-manual"><input type="datetime-local" value={choice.checkInTime||""} onChange={e=>choose(row.scheduleId,{checkInTime:e.target.value})}/><input type="datetime-local" value={choice.checkOutTime||""} onChange={e=>choose(row.scheduleId,{checkOutTime:e.target.value})}/></span>}</td><td>{row.checkIn?row.checkIn.replace("T"," "):"—"}</td><td>{row.checkOut?row.checkOut.replace("T"," "):"—"}</td><td><b>{duration(row.total)}</b></td><td>{row.late} phút</td><td>{row.early} phút</td><td>{row.hasAttendance?<span className="attendance-test-existing">{row.attendanceStatus||"Đã có"}</span>:"—"}</td></tr>})}</tbody></table></div>
  </section></div>;
}
