import { useEffect, useState } from "react";
import { FiCamera, FiEdit2, FiEye, FiGitBranch, FiKey, FiLock, FiPlus, FiSearch, FiTrash2, FiUnlock, FiUserX, FiX } from "react-icons/fi";
import { managerEmployeeApi } from "../../api/services";
import { getSession } from "../../utils/auth";
import { Link, useParams, useSearchParams } from "react-router-dom";

const emptyForm={fullName:"",email:"",phone:"",password:"",confirmPassword:"",employeeCode:"",birthDate:"",gender:"",employmentType:"",address:"",identityNumber:"",identityIssueDate:"",identityIssuePlace:"",bankAccountNumber:"",bankName:"",bankBranch:"",hireDate:new Date().toISOString().slice(0,10),baseSalary:"0",branchId:"",positionId:"",roleCode:"employee",employeeStatus:"working",accountStatus:"active",avatarUrl:""};
const dateInput=value=>value?String(value).slice(0,10):"";
const money=value=>new Intl.NumberFormat("vi-VN").format(Number(value)||0);
const empLabels={working:"Đang làm",on_leave:"Nghỉ phép",resigned:"Đã nghỉ việc"};
const accountLabels={active:"Hoạt động",inactive:"Ngừng hoạt động",locked:"Đã khóa"};

function EmployeeModal({mode,employee,branches,positions,fixedBranchId,onClose,onSaved,onEdit}){
  const {role:actorRole}=getSession();
  const [form,setForm]=useState(()=>employee?{...emptyForm,...employee,birthDate:dateInput(employee.birthDate),identityIssueDate:dateInput(employee.identityIssueDate),hireDate:dateInput(employee.hireDate),branchId:String(employee.branchId),positionId:String(employee.positionId),baseSalary:String(employee.baseSalary??0)}:{...emptyForm,branchId:String(fixedBranchId||"")});
  const [errors,setErrors]=useState({}),[loading,setLoading]=useState(false);
  const readonly=mode==="view",edit=mode==="edit";
  const set=(key,value)=>{setForm(v=>({...v,[key]:value}));setErrors(v=>({...v,[key]:""}))};
  async function submit(e){e.preventDefault();const next={};["fullName","email","employeeCode","hireDate","branchId","positionId"].forEach(k=>{if(!String(form[k]||"").trim())next[k]="Trường này là bắt buộc"});if(!edit&&form.password.length<6)next.password="Mật khẩu phải có ít nhất 6 ký tự";if(!edit&&form.password!==form.confirmPassword)next.confirmPassword="Mật khẩu xác nhận không khớp";if(Object.keys(next).length)return setErrors(next);setLoading(true);try{const payload={...form,branchId:Number(form.branchId),positionId:Number(form.positionId),baseSalary:Number(form.baseSalary||0)};const r=edit?await managerEmployeeApi.update(employee.id,payload):await managerEmployeeApi.create(payload);onSaved(r.data,edit?"Cập nhật nhân viên thành công":"Tạo nhân viên thành công")}catch(error){const data=error.response?.data||{};if(data.field)setErrors({[data.field]:data.message});else setErrors({form:data.message||"Không thể lưu nhân viên"})}finally{setLoading(false)}}
  async function toggleProfileLock(){setLoading(true);try{const response=await managerEmployeeApi.profileUpdateLock(employee.id,!employee.profileUpdateLocked);onSaved(response.data,response.message)}catch(error){setErrors({form:error.response?.data?.message||"Không thể cập nhật quyền sửa hồ sơ"})}finally{setLoading(false)}}
  async function changeAvatar(event){const file=event.target.files?.[0];event.target.value="";if(!file)return;if(file.size>5*1024*1024)return setErrors({form:"Ảnh đại diện không được lớn hơn 5 MB"});setLoading(true);setErrors({});try{const response=await managerEmployeeApi.updateAvatar(employee.id,file);onSaved(response.data,response.message)}catch(error){setErrors({form:error.response?.data?.message||"Không thể cập nhật ảnh đại diện"})}finally{setLoading(false)}}
  const personalReadonly=key=>["identityNumber","identityIssueDate","identityIssuePlace","bankAccountNumber","bankName","bankBranch"].includes(key);
  const field=(key,label,type="text",required=false)=><label>{label}{required&&" *"}<input type={type} disabled={readonly||(edit&&key==="employeeCode")||personalReadonly(key)} value={form[key]??""} onChange={e=>set(key,e.target.value)} />{errors[key]&&<small className="field-error">{errors[key]}</small>}</label>;
  return <div className="manager-modal-backdrop"><form className="employee-modal" onSubmit={submit}><header><div><h2>{readonly?"Chi tiết nhân viên":edit?"Chỉnh sửa nhân viên":"Thêm nhân viên"}</h2></div><button type="button" onClick={onClose}><FiX/></button></header>{errors.form&&<div className="manager-form-error">{errors.form}</div>}{employee&&<div className="admin-employee-identity"><label className="admin-employee-avatar-editor" title="Đổi ảnh đại diện">{employee.avatarUrl?<img src={employee.avatarUrl} alt={`Ảnh đại diện ${employee.fullName}`}/>:<span>{employee.fullName.split(/\s+/).slice(-2).map(value=>value[0]).join("").toUpperCase()}</span>}<i><FiCamera/></i><input type="file" accept="image/jpeg,image/png,image/webp" onChange={changeAvatar} disabled={loading||actorRole!=="admin"}/></label><div><b>{employee.fullName}</b><small>{employee.employeeCode} · {employee.positionName}</small>{actorRole==="admin"&&<small>{loading?"Đang tải ảnh...":"Bấm vào ảnh để thay đổi"}</small>}</div></div>}
    <fieldset disabled={loading}><section><h3>A. Tài khoản</h3><div className="employee-form-grid">{field("fullName","Họ và tên","text",true)}{field("email","Email đăng nhập","email",true)}{field("phone","Số điện thoại")}{!edit&&!readonly&&field("password","Mật khẩu ban đầu","password",true)}{!edit&&!readonly&&field("confirmPassword","Xác nhận mật khẩu","password",true)}{!edit&&!readonly&&<label>Quyền tài khoản<select value={form.roleCode} onChange={e=>set("roleCode",e.target.value)}><option value="employee">Nhân viên</option>{actorRole==="admin"&&<option value="manager">Quản lý</option>}{actorRole==="admin"&&<option value="admin">Admin</option>}</select>{errors.roleCode&&<small className="field-error">{errors.roleCode}</small>}</label>}{edit&&<label>Trạng thái tài khoản<select disabled={readonly} value={form.accountStatus} onChange={e=>set("accountStatus",e.target.value)}>{Object.entries(accountLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>}</div></section>
    <section className="admin-profile-information"><h3>B. Thông tin nhân viên</h3>
      <div className="admin-profile-group"><h4><span>1</span> Thông tin cá nhân</h4><div className="employee-form-grid">{field("employeeCode","Mã nhân viên","text",true)}{field("birthDate","Ngày sinh","date")}<label>Giới tính<select disabled={readonly} value={form.gender||""} onChange={e=>set("gender",e.target.value)}><option value="">Chưa cập nhật</option><option value="male">Nam</option><option value="female">Nữ</option><option value="other">Khác</option></select></label>{field("hireDate","Ngày vào làm","date",true)}<label>Hình thức làm việc<select disabled={readonly} value={form.employmentType||""} onChange={e=>set("employmentType",e.target.value)}><option value="">Chưa cập nhật</option><option value="part_time">Part-time</option><option value="full_time">Full-time</option></select></label>{field("baseSalary","Lương cơ bản","number")}{field("address","Địa chỉ")}</div></div>
      <div className="admin-profile-group"><h4><span>2</span> Căn cước công dân</h4><div className="employee-form-grid">{field("identityNumber","Số CCCD")}{field("identityIssueDate","Ngày cấp CCCD","date")}{field("identityIssuePlace","Nơi cấp CCCD")}</div></div>
      <div className="admin-profile-group"><h4><span>3</span> Tài khoản ngân hàng</h4><div className="employee-form-grid">{field("bankAccountNumber","Số tài khoản ngân hàng")}{field("bankName","Tên ngân hàng")}{field("bankBranch","Chi nhánh ngân hàng")}</div></div>
    </section>
    <section><h3>C. Công việc</h3><div className="employee-form-grid"><label>Chi nhánh *<select disabled={readonly||(!edit&&Boolean(fixedBranchId))} value={form.branchId} onChange={e=>set("branchId",e.target.value)}><option value="">Chọn chi nhánh</option>{branches.map(x=><option key={x.id} value={x.id}>{x.branchCode} · {x.branchName}</option>)}</select>{errors.branchId&&<small className="field-error">{errors.branchId}</small>}</label><label>Vị trí *<select disabled={readonly} value={form.positionId} onChange={e=>set("positionId",e.target.value)}><option value="">Chọn vị trí</option>{positions.map(x=><option key={x.id} value={x.id}>{x.positionName}</option>)}</select>{errors.positionId&&<small className="field-error">{errors.positionId}</small>}</label>{edit&&<label>Trạng thái làm việc<select disabled={readonly} value={form.employeeStatus} onChange={e=>set("employeeStatus",e.target.value)}>{Object.entries(empLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>}</div></section></fieldset>
    <footer>{readonly&&actorRole==="admin"&&<button type="button" className={`btn ${employee.profileUpdateLocked?"btn-light":"btn-profile-lock"}`} disabled={loading} onClick={toggleProfileLock}>{employee.profileUpdateLocked?<><FiUnlock/> Mở khóa cập nhật hồ sơ</>:<><FiLock/> Khóa cập nhật hồ sơ</>}</button>}<button type="button" className="btn btn-light" onClick={onClose}>{readonly?"Đóng":"Hủy"}</button>{readonly&&<button type="button" className="btn btn-primary" onClick={()=>onEdit(employee)}><FiEdit2/> Chỉnh sửa</button>}{!readonly&&<button className="btn btn-primary" disabled={loading}>{loading?"Đang lưu...":"Lưu nhân viên"}</button>}</footer></form></div>
}

function BranchModal({onClose,onSaved}){
  const [form,setForm]=useState({branchCode:"",branchName:"",phone:"",address:""}),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  async function submit(event){event.preventDefault();setError("");if(!form.branchCode.trim()||!form.branchName.trim())return setError("Vui lòng nhập mã và tên chi nhánh");setLoading(true);try{const response=await managerEmployeeApi.createBranch(form);onSaved(response.data,response.message)}catch(e){setError(e.response?.data?.message||"Không thể thêm chi nhánh")}finally{setLoading(false)}}
  return <div className="manager-modal-backdrop"><form className="employee-modal branch-modal" onSubmit={submit}><header><div><h2>Thêm chi nhánh</h2><p>Chi nhánh mới được lưu trực tiếp vào SQL Server.</p></div><button type="button" onClick={onClose}><FiX/></button></header>{error&&<div className="manager-form-error">{error}</div>}<fieldset disabled={loading}><section><div className="employee-form-grid"><label>Mã chi nhánh *<input value={form.branchCode} onChange={e=>setForm({...form,branchCode:e.target.value})} placeholder="VD: CNQ7"/></label><label>Tên chi nhánh *<input value={form.branchName} onChange={e=>setForm({...form,branchName:e.target.value})} placeholder="Chi nhánh Quận 7"/></label><label>Số điện thoại<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Địa chỉ<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label></div></section></fieldset><footer><button type="button" className="btn btn-light" onClick={onClose}>Hủy</button><button className="btn btn-primary" disabled={loading}>{loading?"Đang lưu...":"Thêm chi nhánh"}</button></footer></form></div>
}

export default function EmployeesPage(){
  const {branchId}=useParams(),[searchParams]=useSearchParams();
  const [items,setItems]=useState([]),[branches,setBranches]=useState([]),[positions,setPositions]=useState([]),[pagination,setPagination]=useState({page:1,total:0,totalPages:1}),[filters,setFilters]=useState({search:"",positionId:"",employeeStatus:"",accountStatus:""}),[query,setQuery]=useState(filters),[modal,setModal]=useState(null),[message,setMessage]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[quickOpen,setQuickOpen]=useState(false),[quickCode,setQuickCode]=useState(""),[quickBusy,setQuickBusy]=useState(false);
  const load=(page=pagination.page)=>{setLoading(true);setError("");managerEmployeeApi.list({...query,branchId,page,limit:10}).then(r=>{setItems(r.data);setPagination(r.pagination)}).catch(e=>setError(e.response?.data?.message||"Không tải được danh sách")).finally(()=>setLoading(false))};
  useEffect(()=>{Promise.all([managerEmployeeApi.branches(),managerEmployeeApi.positions()]).then(([b,p])=>{setBranches(b.data);setPositions(p.data)}).catch(()=>setError("Không tải được danh mục"))},[]);
  useEffect(()=>{load(1)},[query,branchId]);
  useEffect(()=>{if(searchParams.get("create")==="1")setModal({mode:"create"});const employeeId=Number(searchParams.get("employee")||0);if(employeeId)managerEmployeeApi.get(employeeId).then(r=>setModal({mode:"view",employee:r.data})).catch(e=>setError(e.response?.data?.message||"Không tải được nhân viên"))},[searchParams]);
  function saved(_,text){setModal(null);setMessage(text);load()}
  async function status(item){const next=item.accountStatus==="active"?"locked":"active";if(!window.confirm(`${next==="locked"?"Khóa":"Mở"} tài khoản ${item.fullName}?`))return;try{const r=await managerEmployeeApi.accountStatus(item.id,next);setMessage(r.message);load()}catch(e){setError(e.response?.data?.message||"Thao tác thất bại")}}
  async function reset(item){const password=window.prompt(`Mật khẩu mới cho ${item.fullName} (ít nhất 6 ký tự):`);if(password===null)return;try{const r=await managerEmployeeApi.resetPassword(item.id,password);setMessage(r.message)}catch(e){setError(e.response?.data?.message||"Không thể đặt lại mật khẩu")}}
  async function resign(item){if(!window.confirm(`Xác nhận cho ${item.fullName} nghỉ việc? Dữ liệu lịch sử vẫn được giữ lại.`))return;try{const r=await managerEmployeeApi.resign(item.id,"Nghỉ việc theo cập nhật của quản lý");setMessage(r.message);load()}catch(e){setError(e.response?.data?.message||"Thao tác thất bại")}}
  async function remove(item){setMessage("");setError("");if(!window.confirm(`Xóa vĩnh viễn nhân viên ${item.fullName} và tài khoản đăng nhập?`))return;try{const response=await managerEmployeeApi.remove(item.id);setMessage(response.message);load()}catch(e){setError(e.response?.data?.message||"Không thể xóa nhân viên")}}
  async function quickFind(event){event.preventDefault();const normalized=quickCode.trim().toUpperCase();if(!normalized)return setError("Vui lòng nhập mã nhân viên");setQuickBusy(true);setError("");setMessage("");try{const result=await managerEmployeeApi.list({branchId,search:normalized,page:1,limit:100}),employee=(result.data||[]).find(x=>String(x.employeeCode||"").trim().toUpperCase()===normalized);if(!employee)return setError(`Không tìm thấy nhân viên có mã ${normalized} trong chi nhánh này`);const detail=await managerEmployeeApi.get(employee.id);setQuickOpen(false);setQuickCode("");setModal({mode:"view",employee:detail.data})}catch(e){setError(e.response?.data?.message||"Không thể tìm nhân viên")}finally{setQuickBusy(false)}}
  function branchSaved(branch,text){setBranches(value=>[...value,branch].sort((a,b)=>a.branchName.localeCompare(b.branchName,"vi")));setModal(null);setMessage(text)}
  const branch=branches.find(item=>Number(item.id)===Number(branchId));
  return <section className="card list-card manager-employees"><div className="employee-branch-breadcrumb"><Link to="/manager/employees">Nhân viên</Link><span>→</span><b>{branch?.branchName||"Chi nhánh"}</b></div><div className="section-title"><div><h2>{branch?.branchName||"Nhân viên chi nhánh"}</h2><p>{branch?.branchCode}{branch?.address?` · ${branch.address}`:""} · {pagination.total} nhân viên</p></div><div className="employee-head-actions"><button className="btn btn-light" onClick={()=>{setQuickOpen(true);setError("")}}><FiSearch/> Tìm nhanh nhân viên</button><button className="btn btn-primary" onClick={()=>setModal({mode:"create"})}><FiPlus/> Thêm nhân viên</button></div></div>{message&&<div className="manager-form-success">{message}</div>}{error&&<div className="manager-form-error">{error}</div>}
    <form className="employee-filters branch-employee-filters" onSubmit={e=>{e.preventDefault();setQuery(filters)}}><div className="search"><FiSearch/><input value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} placeholder="Tên, email, mã, số điện thoại..."/></div><select value={filters.positionId} onChange={e=>setFilters({...filters,positionId:e.target.value})}><option value="">Tất cả vị trí</option>{positions.map(x=><option key={x.id} value={x.id}>{x.positionName}</option>)}</select><select value={filters.employeeStatus} onChange={e=>setFilters({...filters,employeeStatus:e.target.value})}><option value="">Trạng thái nhân viên</option>{Object.entries(empLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select value={filters.accountStatus} onChange={e=>setFilters({...filters,accountStatus:e.target.value})}><option value="">Trạng thái tài khoản</option>{Object.entries(accountLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><button className="btn btn-primary">Lọc</button></form>
    <div className="table-wrap"><table><thead><tr>{["Mã NV","Họ tên / Email","Điện thoại","Vị trí","Ngày vào làm","Nhân viên","Tài khoản","Thao tác"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan="8" className="employee-table-empty">Đang tải...</td></tr>:items.length===0?<tr><td colSpan="8" className="employee-table-empty">Chi nhánh này chưa có nhân viên.</td></tr>:items.map(item=><tr key={item.id}><td><b>{item.employeeCode}</b></td><td><div className="name-cell"><div className="avatar">{item.fullName.split(/\s+/).slice(-2).map(x=>x[0]).join("")}</div><div><b>{item.fullName}</b><small>{item.email}</small></div></div></td><td>{item.phone||"—"}</td><td>{item.positionName}</td><td>{dateInput(item.hireDate).split("-").reverse().join("/")}</td><td><span className={`status ${item.employeeStatus==="working"?"success":item.employeeStatus==="on_leave"?"warning":"neutral"}`}>{empLabels[item.employeeStatus]||item.employeeStatus}</span></td><td><span className={`status ${item.accountStatus==="active"?"success":item.accountStatus==="locked"?"warning":"neutral"}`}>{accountLabels[item.accountStatus]}</span></td><td><div className="employee-actions"><button title="Xem" onClick={()=>setModal({mode:"view",employee:item})}><FiEye/></button><button title="Sửa" onClick={()=>setModal({mode:"edit",employee:item})}><FiEdit2/></button><button title={item.accountStatus==="active"?"Khóa":"Mở"} onClick={()=>status(item)}>{item.accountStatus==="active"?<FiLock/>:<FiUnlock/>}</button><button title="Đặt mật khẩu" onClick={()=>reset(item)}><FiKey/></button><button className="danger" title="Cho nghỉ việc" disabled={item.employeeStatus==="resigned"} onClick={()=>resign(item)}><FiUserX/></button><button className="danger" title="Xóa nhân viên" onClick={()=>remove(item)}><FiTrash2/></button></div></td></tr>)}</tbody></table></div>
    <div className="pagination"><span>Hiển thị {items.length} trong {pagination.total} nhân viên</span><div><button disabled={pagination.page<=1} onClick={()=>load(pagination.page-1)}>‹</button>{Array.from({length:pagination.totalPages},(_,i)=>i+1).slice(Math.max(0,pagination.page-3),pagination.page+2).map(p=><button className={p===pagination.page?"active":""} key={p} onClick={()=>load(p)}>{p}</button>)}<button disabled={pagination.page>=pagination.totalPages} onClick={()=>load(pagination.page+1)}>›</button></div></div>
    {quickOpen&&<div className="manager-modal-backdrop"><form className="employee-quick-modal" onSubmit={quickFind}><header><div><h2>Tìm nhanh nhân viên</h2><p>Nhập mã nhân viên trong chi nhánh này</p></div><button type="button" onClick={()=>setQuickOpen(false)}><FiX/></button></header><label>Mã nhân viên<input autoFocus value={quickCode} onChange={e=>setQuickCode(e.target.value)} placeholder="Ví dụ: CT_03"/></label><footer><button type="button" className="btn btn-light" onClick={()=>setQuickOpen(false)}>Hủy</button><button className="btn btn-primary" disabled={quickBusy}>{quickBusy?"Đang tìm...":"Xem thông tin"}</button></footer></form></div>}{modal&&<EmployeeModal {...modal} fixedBranchId={branchId} branches={branches} positions={positions} onClose={()=>setModal(null)} onSaved={saved} onEdit={employee=>setModal({mode:"edit",employee})}/>}</section>
}
