import {useEffect,useMemo,useState} from "react";
import {FiArrowRight,FiEdit2,FiGitBranch,FiMapPin,FiPhone,FiPlus,FiSearch,FiTrash2,FiUsers,FiX} from "react-icons/fi";
import {Link,useNavigate} from "react-router-dom";
import {managerEmployeeApi} from "../../api/services";
import {getSession} from "../../utils/auth";

export default function EmployeeBranchesPage(){
 const navigate=useNavigate(),{role}=getSession(),[items,setItems]=useState([]),[search,setSearch]=useState(""),[status,setStatus]=useState("");
 const [loading,setLoading]=useState(true),[error,setError]=useState(""),[showCreate,setShowCreate]=useState(false),[branchForm,setBranchForm]=useState({branchCode:"",branchName:"",phone:"",address:""}),[employeeCode,setEmployeeCode]=useState(""),[findingEmployee,setFindingEmployee]=useState(false);
 const [editingBranch,setEditingBranch]=useState(null),[editBranchForm,setEditBranchForm]=useState({branchName:"",phone:"",address:""}),[notice,setNotice]=useState(""),[branchToDelete,setBranchToDelete]=useState(null),[deletingBranchId,setDeletingBranchId]=useState(null);
 const load=()=>{setLoading(true);setError("");return managerEmployeeApi.employeeBranches({search,status}).then(response=>setItems(response.data||[])).catch(e=>setError(e.response?.data?.message||"Không tải được danh sách chi nhánh")).finally(()=>setLoading(false))};
 useEffect(()=>{const timer=setTimeout(load,search?250:0);return()=>clearTimeout(timer)},[search,status]);
 async function createBranch(event){event.preventDefault();setError("");try{await managerEmployeeApi.createBranch(branchForm);setShowCreate(false);setBranchForm({branchCode:"",branchName:"",phone:"",address:""});load()}catch(e){setError(e.response?.data?.message||"Không thể thêm chi nhánh")}}
 function openEdit(branch){setEditingBranch(branch);setEditBranchForm({branchName:branch.branchName||"",phone:branch.phone||"",address:branch.address||""});setError("");setNotice("")}
 async function updateBranch(event){event.preventDefault();setError("");setNotice("");try{const response=await managerEmployeeApi.updateBranch(editingBranch.branchId,{...editBranchForm,branchName:editBranchForm.branchName.trim()});setEditingBranch(null);setNotice(response.message||"Cập nhật thông tin chi nhánh thành công");load()}catch(e){setError(e.response?.data?.message||"Không thể cập nhật thông tin chi nhánh")}}
 async function deleteBranch(){
  const branch=branchToDelete;if(!branch)return;
  setDeletingBranchId(branch.branchId);setError("");setNotice("");
  try{const response=await managerEmployeeApi.deleteBranch(branch.branchId);setBranchToDelete(null);setNotice(response.message||"Đã xóa chi nhánh");await load()}catch(e){setBranchToDelete(null);setError(e.response?.data?.message||"Không thể xóa chi nhánh")}finally{setDeletingBranchId(null)}
 }
 async function findEmployee(event){event.preventDefault();const code=employeeCode.trim().toUpperCase();if(!code)return setError("Vui lòng nhập mã nhân viên");setFindingEmployee(true);setError("");try{const response=await managerEmployeeApi.list({search:code,page:1,limit:100}),employee=(response.data||[]).find(x=>String(x.employeeCode||"").trim().toUpperCase()===code);if(!employee)return setError(`Không tìm thấy nhân viên có mã ${code}`);navigate(`/manager/employees/branch/${employee.branchId}?employee=${employee.id}`)}catch(e){setError(e.response?.data?.message||"Không thể tìm nhân viên")}finally{setFindingEmployee(false)}}
 const totals=useMemo(()=>items.reduce((sum,item)=>sum+Number(item.totalEmployees||0),0),[items]);
 return <section className="manager-branch-page">
  <div className="employee-page-title"><div><h1>Quản lý nhân viên</h1><p>Chọn chi nhánh để xem và quản lý nhân viên.</p></div><div className="branch-directory-actions"><div className="branch-total"><FiUsers/><b>{totals}</b><span>nhân viên</span></div><button className="btn btn-primary" onClick={()=>setShowCreate(true)}><FiPlus/> Thêm chi nhánh</button></div></div>
  <form className="employee-global-lookup" onSubmit={findEmployee}><div><FiSearch/><input autoComplete="off" value={employeeCode} onChange={e=>setEmployeeCode(e.target.value)} placeholder="Nhập mã nhân viên, ví dụ CT_03"/></div><button className="btn btn-primary" disabled={findingEmployee}>{findingEmployee?"Đang tìm...":"Xem toàn bộ thông tin"}</button></form>
  <div className="branch-directory-tools"><label><FiSearch/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm tên, mã hoặc địa chỉ chi nhánh"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả trạng thái</option><option value="active">Đang hoạt động</option><option value="inactive">Ngừng hoạt động</option></select></div>
  {error&&<div className="manager-form-error">{error}</div>}
  {notice&&<div className="manager-form-success">{notice}</div>}
  {loading?<div className="branch-card-grid">{[1,2].map(item=><i className="branch-card-skeleton" key={item}/>)}</div>:items.length?<div className="branch-card-grid">{items.map(branch=><article className="branch-card" key={branch.branchId} onClick={()=>navigate(`/manager/employees/branch/${branch.branchId}`)}>
   <header><span><FiGitBranch/></span><div><h2>{branch.branchName}</h2><small>{branch.branchCode}</small></div><b className={`branch-status ${branch.status}`}>{branch.status==="active"?"Đang hoạt động":"Ngừng hoạt động"}</b></header>
   <div className="branch-contact"><p><FiMapPin/>{branch.address||"Chưa cập nhật địa chỉ"}</p><p><FiPhone/>{branch.phone||"Chưa cập nhật số điện thoại"}</p></div>
   <div className="branch-stats"><span><b>{branch.totalEmployees}</b><small>Nhân viên</small></span><span><b>{branch.workingEmployees}</b><small>Đang làm</small></span><span><b>{branch.resignedEmployees}</b><small>Đã nghỉ</small></span><span><b>{branch.lockedAccounts}</b><small>TK khóa/ngừng</small></span></div>
   <footer><Link onClick={e=>e.stopPropagation()} to={`/manager/employees/branch/${branch.branchId}`}><span>Xem nhân viên</span><FiArrowRight/></Link><button className="branch-edit-btn" onClick={e=>{e.stopPropagation();openEdit(branch)}}><FiEdit2/> Sửa thông tin</button>{role==="admin"&&branch.status==="active"&&<button className="branch-delete-btn" disabled={deletingBranchId===branch.branchId} onClick={e=>{e.stopPropagation();setBranchToDelete(branch)}}><FiTrash2/> {deletingBranchId===branch.branchId?"Đang xóa":"Xóa"}</button>}</footer>
  </article>)}</div>:<div className="card employee-table-empty">Chưa có chi nhánh trong hệ thống</div>}
  {showCreate&&<div className="manager-modal-backdrop"><form className="employee-modal branch-modal" onSubmit={createBranch}><header><div><h2>Thêm chi nhánh</h2><p>Dữ liệu được lưu trực tiếp vào SQL Server.</p></div><button type="button" onClick={()=>setShowCreate(false)}><FiX/></button></header><fieldset><section><div className="employee-form-grid"><label>Mã chi nhánh *<input required value={branchForm.branchCode} onChange={e=>setBranchForm({...branchForm,branchCode:e.target.value})}/></label><label>Tên chi nhánh *<input required value={branchForm.branchName} onChange={e=>setBranchForm({...branchForm,branchName:e.target.value})}/></label><label>Số điện thoại<input value={branchForm.phone} onChange={e=>setBranchForm({...branchForm,phone:e.target.value})}/></label><label>Địa chỉ<input value={branchForm.address} onChange={e=>setBranchForm({...branchForm,address:e.target.value})}/></label></div></section></fieldset><footer><button type="button" className="btn btn-light" onClick={()=>setShowCreate(false)}>Hủy</button><button className="btn btn-primary">Thêm chi nhánh</button></footer></form></div>}
  {editingBranch&&<div className="manager-modal-backdrop"><form className="employee-modal branch-modal" onSubmit={updateBranch}><header><div><h2>Sửa thông tin chi nhánh</h2><p>Mã chi nhánh: {editingBranch.branchCode}</p></div><button type="button" onClick={()=>setEditingBranch(null)}><FiX/></button></header><fieldset><section><div className="employee-form-grid"><label>Tên chi nhánh *<input autoFocus required maxLength="150" value={editBranchForm.branchName} onChange={e=>setEditBranchForm({...editBranchForm,branchName:e.target.value})}/></label><label>Số điện thoại<input maxLength="20" value={editBranchForm.phone} onChange={e=>setEditBranchForm({...editBranchForm,phone:e.target.value})}/></label><label className="wide">Địa chỉ<input maxLength="300" value={editBranchForm.address} onChange={e=>setEditBranchForm({...editBranchForm,address:e.target.value})}/></label></div></section></fieldset><footer><button type="button" className="btn btn-light" onClick={()=>setEditingBranch(null)}>Hủy</button><button className="btn btn-primary" disabled={!editBranchForm.branchName.trim()}>Lưu thay đổi</button></footer></form></div>}
  {branchToDelete&&<div className="manager-modal-backdrop branch-delete-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!deletingBranchId)setBranchToDelete(null)}}><section className="branch-delete-confirm" role="dialog" aria-modal="true" aria-labelledby="branch-delete-title"><button className="branch-delete-close" type="button" aria-label="Đóng" disabled={Boolean(deletingBranchId)} onClick={()=>setBranchToDelete(null)}><FiX/></button><div className="branch-delete-icon"><FiTrash2/></div><h2 id="branch-delete-title">Xóa vĩnh viễn chi nhánh?</h2><p>Thao tác này không thể hoàn tác.</p><div className="branch-delete-target"><small>Chi nhánh sẽ bị xóa</small><b>{branchToDelete.branchName}</b><span>{branchToDelete.branchCode} · {branchToDelete.totalEmployees} nhân viên</span></div><p className="branch-delete-warning">Mọi dữ liệu liên quan sẽ bị xóa: nhân viên, tài khoản, lịch làm, đăng ký ca, chấm công, báo cáo, kho, giao dịch và tin nhắn.</p><footer><button type="button" className="btn btn-light" disabled={Boolean(deletingBranchId)} onClick={()=>setBranchToDelete(null)}>Hủy</button><button type="button" className="btn branch-confirm-delete" disabled={Boolean(deletingBranchId)} onClick={deleteBranch}><FiTrash2/> {deletingBranchId?"Đang xóa...":"Xóa tất cả"}</button></footer></section></div>}
 </section>
}
