import {useEffect,useState} from 'react';
import {FiCheckCircle,FiClipboard,FiPackage,FiRefreshCw} from 'react-icons/fi';
import {branchReportApi,managerEmployeeApi} from '../../api/services';

const today=()=>new Date().toISOString().slice(0,10);
const info={HYGIENE:{title:'Báo cáo vệ sinh',icon:FiClipboard,placeholder:'Khu vực đã vệ sinh, vấn đề phát hiện, việc cần xử lý...'},GOODS:{title:'Báo cáo hàng hóa',icon:FiPackage,placeholder:'Hàng thiếu, hư hỏng, gần hết hạn hoặc cần nhập thêm...'}};
export default function OperationalReports({type}){
  const [branches,setBranches]=useState([]),[branchId,setBranchId]=useState(''),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState('');
  const [form,setForm]=useState({reportDate:today(),title:'',content:'',score:''});const meta=info[type],Icon=meta.icon;
  async function load(){try{setLoading(true);setError('');const response=await branchReportApi.list({type,...(branchId?{branchId}:{})});setItems(response.data||[])}catch(e){setError(e.response?.data?.message||'Không tải được báo cáo')}finally{setLoading(false)}}
  useEffect(()=>{managerEmployeeApi.branches().then(r=>setBranches(r.data||[])).catch(()=>{})},[]);useEffect(()=>{load()},[type,branchId]);
  async function submit(event){event.preventDefault();try{setError('');setSuccess('');await branchReportApi.create({...form,branchId,reportType:type});setForm({reportDate:today(),title:'',content:'',score:''});setSuccess('Đã gửi báo cáo thành công');load()}catch(e){setError(e.response?.data?.message||'Không gửi được báo cáo')}}
  async function review(id,status){try{await branchReportApi.review(id,status);load()}catch(e){setError(e.response?.data?.message||'Không cập nhật được báo cáo')}}
  return <div className="operational-reports"><section className="card operational-report-head"><div><Icon/><div><h1>{meta.title}</h1><p>Theo dõi riêng cho từng chi nhánh.</p></div></div><label>Chi nhánh<select value={branchId} onChange={e=>setBranchId(e.target.value)}><option value="">Tất cả chi nhánh</option>{branches.map(b=><option key={b.id} value={b.id}>{b.branchName}</option>)}</select></label><button className="btn btn-light" onClick={load}><FiRefreshCw/> Tải lại</button></section>
    <section className="operational-report-grid"><form className="card operational-report-form" onSubmit={submit}><h2>Tạo báo cáo mới</h2>{error&&<div className="manager-form-error">{error}</div>}{success&&<div className="manager-form-success">{success}</div>}<label>Chi nhánh *<select required value={form.branchId||branchId} onChange={e=>{setBranchId(e.target.value);setForm(v=>({...v,branchId:e.target.value}))}}><option value="">Chọn chi nhánh</option>{branches.map(b=><option key={b.id} value={b.id}>{b.branchName}</option>)}</select></label><label>Ngày báo cáo *<input required type="date" value={form.reportDate} onChange={e=>setForm(v=>({...v,reportDate:e.target.value}))}/></label><label>Tiêu đề *<input required maxLength={200} value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></label><label>Điểm đánh giá (0–100)<input type="number" min="0" max="100" value={form.score} onChange={e=>setForm(v=>({...v,score:e.target.value}))}/></label><label>Nội dung *<textarea required maxLength={2000} rows="7" placeholder={meta.placeholder} value={form.content} onChange={e=>setForm(v=>({...v,content:e.target.value}))}/></label><button className="btn btn-yellow">Gửi báo cáo</button></form>
      <section className="operational-report-list">{loading?<div className="card empty-state">Đang tải...</div>:items.length?items.map(item=><article className="card" key={item.id}><header><div><b>{item.title}</b><small>{item.branchName} · {new Date(item.reportDate+'T00:00:00').toLocaleDateString('vi-VN')}</small></div><span className={`report-status ${item.status}`}>{item.status==='approved'?'Đã duyệt':item.status==='needs_action'?'Cần xử lý':'Chờ duyệt'}</span></header><p>{item.content}</p><footer><span>Người gửi: <b>{item.createdBy}</b>{item.score!=null&&<> · Điểm: <b>{item.score}/100</b></>}</span>{item.status==='submitted'&&<div><button onClick={()=>review(item.id,'needs_action')}>Cần xử lý</button><button className="approve" onClick={()=>review(item.id,'approved')}><FiCheckCircle/> Duyệt</button></div>}</footer></article>):<div className="card empty-state">Chưa có {meta.title.toLowerCase()}.</div>}</section></section></div>;
}
