import {useEffect,useMemo,useState} from "react";
import {useNavigate,useParams} from "react-router-dom";
import {scheduleRegistrationApi} from "../../api/services";
import {parseShiftDisplayCode} from "../../utils/shiftCode";
const iso=v=>v instanceof Date?`${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,"0")}-${String(v.getDate()).padStart(2,"0")}`:String(v||"").slice(0,10);
const range=(a,b)=>{a=new Date(`${iso(a)}T00:00:00`);b=new Date(`${iso(b)}T00:00:00`);return Array.from({length:Math.floor((b-a)/864e5)+1},(_,i)=>{const d=new Date(a);d.setDate(a.getDate()+i);return d})};
const days=["CN","T2","T3","T4","T5","T6","T7"],clock=v=>{const m=String(v||"").match(/T(\d{2}):(\d{2})/)||String(v||"").match(/^(\d{2}):(\d{2})/);return m?`${m[1]}:${m[2]}`:""};
const preferenceCodes={morning:new Set(["A","P1","FULL"]),afternoon:new Set(["B","P2","P3","FULL"])};
export default function ScheduleBuilderPage(){
 const {periodId}=useParams(),navigate=useNavigate(),[data,setData]=useState(null),[assignments,setAssignments]=useState({}),[selectedEmployeeId,setSelectedEmployeeId]=useState(null),[message,setMessage]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const absorb=p=>{const registrationMap={};p.registrations.forEach(x=>registrationMap[`${x.employeeId}_${x.workDate}`]=x.shiftCode);return {...p,registrationMap}};
 useEffect(()=>{scheduleRegistrationApi.builder(periodId).then(({data:p})=>{const draft={};p.draftSchedules.forEach(x=>draft[`${x.employeeId}_${x.workDate}`]={shiftCode:x.shiftCode,displayCode:x.displayCode||x.shiftCode,startTime:clock(x.startTime),endTime:clock(x.endTime),workPosition:x.workPosition||"",note:x.note||""});setData(absorb(p));setAssignments(draft)}).catch(e=>setError(e.response?.data?.message||"Không tải được dữ liệu xếp lịch"))},[periodId]);
 useEffect(()=>{const timer=setInterval(()=>scheduleRegistrationApi.builder(periodId).then(({data:p})=>setData(current=>current?{...current,...absorb(p)}:current)).catch(()=>{}),3000);return()=>clearInterval(timer)},[periodId]);
 const dates=useMemo(()=>data?range(data.period.startDate,data.period.endDate):[],[data]);
 const change=(key,field,value)=>setAssignments(old=>({...old,[key]:{...(old[key]||{}),[field]:value}}));
 const changeCode=(key,value)=>setAssignments(old=>{const current=old[key]||{},parsed=parseShiftDisplayCode(value);return {...old,[key]:{...current,displayCode:value.toUpperCase(),...(parsed?{shiftCode:parsed.baseShiftCode,startTime:parsed.startTime,endTime:parsed.endTime,codeError:""}:{codeError:"Nhập mã như A+2, P3-1, P2+P3-0.5, AB hoặc 10h-23h."})}}});
 const choose=(key,code)=>{if(!code)return setAssignments(old=>{const next={...old};delete next[key];return next});const shift=data.shifts.find(x=>x.shiftCode===code);setAssignments(old=>({...old,[key]:{...(old[key]||{}),shiftCode:code,displayCode:code,startTime:clock(shift.startTime),endTime:clock(shift.endTime)}}))};
 const schedules=()=>Object.entries(assignments).filter(([,x])=>x.shiftCode).map(([key,x])=>{const cut=key.indexOf("_"),employeeId=Number(key.slice(0,cut)),employee=data.employees.find(e=>Number(e.employeeId)===employeeId);return {...x,employeeId,workDate:key.slice(cut+1),workPosition:x.workPosition||employee?.positionName||"",note:x.note||""}});
 const run=async publish=>{setSaving(true);setError("");setMessage("");try{const invalid=Object.values(assignments).find(x=>x.codeError);if(invalid)throw new Error(invalid.codeError);await scheduleRegistrationApi.saveBuilder(periodId,schedules());if(publish){const r=await scheduleRegistrationApi.publishBuilder(periodId);setMessage(`${r.message}. Ngày không được xếp ca sẽ tính là ngày nghỉ.`)}else setMessage("Đã lưu bản nháp xếp lịch.")}catch(e){setError(e.response?.data?.message||e.message||"Không thể lưu lịch")}finally{setSaving(false)}};
 if(!data)return <section className="card employee-table-empty">Đang tải trình xếp lịch...</section>;
 const head=<thead><tr><th>Nhân viên</th>{dates.map(d=><th key={iso(d)}>{days[d.getDay()]}<small>{d.toLocaleDateString("vi-VN",{day:"2-digit",month:"2-digit"})}</small></th>)}</tr></thead>;
 return <section className="card registration-sheet schedule-builder-page"><div className="section-title"><div><h2>Xếp lịch chính thức</h2><p>{data.period.title} · Xem nguyện vọng ở trên và xếp lịch ở dưới.</p></div><div><button className="btn btn-light" onClick={()=>navigate(-1)}>Quay lại</button>{" "}<button className="btn btn-light" disabled={saving} onClick={()=>run(false)}>Lưu bản nháp</button>{" "}<button className="btn btn-primary" disabled={saving} onClick={()=>run(true)}>Lưu & Công bố</button></div></div>{message&&<div className="manager-form-success">{message}</div>}{error&&<div className="manager-form-error">{error}</div>}
 <section className="builder-preference-calendar"><div className="builder-block-title"><div><h3>Lịch nguyện vọng nhân viên</h3><p>Mỗi nhân viên một hàng; từng ngày được chia rõ buổi sáng và chiều.</p></div><span>Tự động cập nhật</span></div><div className="schedule-sheet-wrap preference-sheet-wrap"><table className="schedule-sheet preference-calendar preference-compact-calendar"><thead><tr><th rowSpan="2">Nhân viên</th>{dates.map(d=><th colSpan="2" key={iso(d)}>{days[d.getDay()]}<small>{d.toLocaleDateString("vi-VN",{day:"2-digit",month:"2-digit"})}</small></th>)}</tr><tr>{dates.flatMap(d=>[<th className="morning" key={`${iso(d)}-morning`}>Sáng</th>,<th className="afternoon" key={`${iso(d)}-afternoon`}>Chiều</th>])}</tr></thead><tbody>{data.employees.map(employee=><tr key={employee.employeeId}><th className="preference-employee-name"><b>{employee.fullName}</b><small>{employee.positionName}</small></th>{dates.flatMap(d=>{const code=data.registrationMap[`${employee.employeeId}_${iso(d)}`]||"";return ["morning","afternoon"].map(band=>{const active=preferenceCodes[band].has(code);return <td className={`compact-preference-cell ${band}`} key={`${iso(d)}-${band}`}>{active?<span className={`preference-employee-choice code-${code.toLowerCase()}`}><b>{code==="FULL"?"Rảnh":code}</b></span>:<span className="preference-employee-rest">—</span>}</td>})})}</tr>)}</tbody></table></div><div className="registration-choice-note">A, P1: sáng · B, P2, P3: chiều · FULL: rảnh cả hai buổi · Ô trống: nghỉ.</div></section>
 <section className="builder-official-calendar"><div className="builder-block-title"><div><h3>Lịch làm việc chính thức</h3><p>Chọn ca và giờ làm dựa trên nguyện vọng phía trên.</p></div></div><div className="schedule-sheet-wrap"><table className="schedule-sheet builder custom-builder">{head}<tbody>{data.employees.map(e=>{const selected=Number(selectedEmployeeId)===Number(e.employeeId);return <tr key={e.employeeId} className={selected?"builder-row-selected":""}><th className="builder-employee-cell" role="button" tabIndex="0" onClick={()=>setSelectedEmployeeId(old=>Number(old)===Number(e.employeeId)?null:e.employeeId)}><b>{e.fullName}</b><small>{e.positionName}</small></th>{dates.map(d=>{const key=`${e.employeeId}_${iso(d)}`,value=assignments[key]||{};return <td key={key} className={value.codeError?"shift-code-invalid":""}><select value={value.shiftCode||""} onChange={ev=>choose(key,ev.target.value)}><option value="">Nghỉ / chưa xếp</option>{data.shifts.map(s=><option key={s.shiftId} value={s.shiftCode}>{s.shiftCode}</option>)}</select>{value.shiftCode&&<div className="custom-shift-fields"><input aria-label="Mã hiển thị" value={value.displayCode||""} onChange={ev=>changeCode(key,ev.target.value)}/><span><input className="shift-time-24h" type="text" inputMode="numeric" maxLength="5" placeholder="18:00" aria-label="Giờ bắt đầu, định dạng 24 giờ" value={value.startTime||""} onChange={ev=>change(key,"startTime",ev.target.value)}/><input className="shift-time-24h" type="text" inputMode="numeric" maxLength="5" placeholder="23:00" aria-label="Giờ kết thúc, định dạng 24 giờ" value={value.endTime||""} onChange={ev=>change(key,"endTime",ev.target.value)}/></span>{value.codeError&&<small className="shift-code-error">{value.codeError}</small>}{!value.codeError&&value.displayCode&&<strong className="shift-time-preview">{value.displayCode}<br/>{value.startTime}–{value.endTime}</strong>}</div>}</td>})}</tr>})}</tbody></table></div><div className="registration-choice-note">Giờ làm dùng định dạng 24 giờ, ví dụ 18:00–23:00. FULL chỉ là nguyện vọng rảnh cả ngày; trước khi công bố phải chọn ca và lưu giờ làm thật.</div></section></section>;
}
