import {useEffect,useMemo,useState} from "react";
import {FiArrowRight,FiCalendar,FiChevronLeft,FiChevronRight,FiClock,FiGitBranch,FiPlus,FiSearch,FiUsers} from "react-icons/fi";
import {useNavigate} from "react-router-dom";
import {environmentApi,managerEmployeeApi,managerScheduleApi,scheduleRegistrationApi} from "../../api/services";

const dayNames=["Chủ nhật","Thứ 2","Thứ 3","Thứ 4","Thứ 5","Thứ 6","Thứ 7"];
const weekNames=["Thứ 2","Thứ 3","Thứ 4","Thứ 5","Thứ 6","Thứ 7","Chủ nhật"];
const dateKey=date=>{const value=date instanceof Date?date:new Date(`${String(date).slice(0,10)}T00:00:00`);return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`};
const mondayOf=date=>{const value=new Date(date);value.setHours(0,0,0,0);value.setDate(value.getDate()-((value.getDay()+6)%7));return value};
const statusLabels={scheduled:"Đã xếp",working:"Đang làm",completed:"Hoàn thành",cancelled:"Đã hủy"};

export default function SchedulePage(){
 const navigate=useNavigate(),today=new Date();
 const [view,setView]=useState("week"),[anchor,setAnchor]=useState(()=>mondayOf(today)),[month,setMonth]=useState(()=>new Date(today.getFullYear(),today.getMonth(),1));
 const [selectedDate,setSelectedDate]=useState(()=>dateKey(today)),[data,setData]=useState({employees:[],schedules:[]});
 const [branches,setBranches]=useState([]),[selectedBranch,setSelectedBranch]=useState(null),[positions,setPositions]=useState([]);
 const [filters,setFilters]=useState({positionId:"",search:""}),[branchSearch,setBranchSearch]=useState("");
 const [loading,setLoading]=useState(false),[branchesLoading,setBranchesLoading]=useState(true),[error,setError]=useState("");
 const days=useMemo(()=>Array.from({length:7},(_,index)=>{const date=new Date(anchor);date.setDate(anchor.getDate()+index);return date}),[anchor]);
 const monthDays=useMemo(()=>{const last=new Date(month.getFullYear(),month.getMonth()+1,0);return Array.from({length:last.getDate()},(_,index)=>new Date(month.getFullYear(),month.getMonth(),index+1))},[month]);
 const monthCells=useMemo(()=>[...Array((monthDays[0].getDay()+6)%7).fill(null),...monthDays],[monthDays]);
 const from=view==="week"?dateKey(days[0]):dateKey(monthDays[0]),to=view==="week"?dateKey(days[6]):dateKey(monthDays.at(-1));

 useEffect(()=>{Promise.all([managerEmployeeApi.employeeBranches({status:"active"}),managerEmployeeApi.positions()]).then(([b,p])=>{setBranches(b.data||[]);setPositions(p.data||[])}).catch(e=>setError(e.response?.data?.message||"Không tải được danh sách chi nhánh")).finally(()=>setBranchesLoading(false))},[]);
 useEffect(()=>{if(!selectedBranch){setData({employees:[],schedules:[]});setLoading(false);return}let active=true;setLoading(true);setError("");setData({employees:[],schedules:[]});const timer=setTimeout(()=>managerScheduleApi.list({branchId:selectedBranch.branchId,positionId:filters.positionId,search:filters.search,from,to}).then(response=>{if(active)setData(response.data)}).catch(e=>{if(active)setError(e.response?.data?.message||"Không tải được lịch làm")}).finally(()=>{if(active)setLoading(false)}),filters.search?250:0);return()=>{active=false;clearTimeout(timer)}},[from,to,selectedBranch,filters.positionId,filters.search]);

 useEffect(()=>{
  if(import.meta.env.VITE_APP_ENV!=="sandbox")return;
  environmentApi.get().then(result=>{
   if(result.appEnv!=="sandbox"||!result.businessDateTime)return;
   const businessDate=new Date(String(result.businessDateTime).replace(/Z$/,"").slice(0,19));
   setAnchor(mondayOf(businessDate));
   setMonth(new Date(businessDate.getFullYear(),businessDate.getMonth(),1));
   setSelectedDate(dateKey(businessDate));
  }).catch(()=>{});
 },[]);

 const visibleBranches=useMemo(()=>{const keyword=branchSearch.trim().toLowerCase();return keyword?branches.filter(branch=>`${branch.branchName} ${branch.branchCode} ${branch.address||""}`.toLowerCase().includes(keyword)):branches},[branches,branchSearch]);
 const employeesById=useMemo(()=>new Map(data.employees.map(item=>[Number(item.employeeId),item])),[data.employees]);
 const scheduleMap=useMemo(()=>data.schedules.reduce((map,item)=>{(map[`${item.employeeId}_${item.workDate}`]??=[]).push(item);return map},{}),[data.schedules]);
 const schedulesByDate=useMemo(()=>data.schedules.reduce((map,item)=>{(map[item.workDate]??=[]).push(item);return map},{}),[data.schedules]);
 const selectedSchedules=schedulesByDate[selectedDate]||[];
 const movePeriod=amount=>{if(view==="week")setAnchor(value=>{const next=new Date(value);next.setDate(value.getDate()+amount*7);return next});else setMonth(value=>{const next=new Date(value.getFullYear(),value.getMonth()+amount,1);setSelectedDate(dateKey(next));return next})};
 const goCurrent=()=>{if(view==="week")setAnchor(mondayOf(new Date()));else{const now=new Date();setMonth(new Date(now.getFullYear(),now.getMonth(),1));setSelectedDate(dateKey(now))}};
 const switchView=next=>{setView(next);if(next==="month"){const reference=new Date(anchor);setMonth(new Date(reference.getFullYear(),reference.getMonth(),1));setSelectedDate(dateKey(reference))}else setAnchor(mondayOf(new Date(`${selectedDate}T00:00:00`)))};

 const openBuilder=async()=>{try{setError("");const response=await scheduleRegistrationApi.periods(),periods=response.data||[],branchId=Number(selectedBranch?.branchId||0),focus=view==="week"?from:selectedDate;const candidates=periods.filter(period=>["open","locked","published"].includes(period.status)&&Number(period.branchId)===branchId);const exact=candidates.find(period=>dateKey(period.weekStartDate)<=focus&&dateKey(period.weekEndDate)>=focus),target=exact||candidates[0];if(!target){setError("Chi nhánh này chưa có đợt đăng ký để xem và xếp lịch.");return}navigate(`/manager/schedules/builder/${target.periodId}`)}catch(e){setError(e.response?.data?.message||"Không tìm được đợt đăng ký để xếp lịch")}};

 if(!selectedBranch)return <section className="manager-schedule-branches"><div className="employee-page-title"><div><h1>Quản lý lịch làm việc</h1><p>Chọn chi nhánh để xem và sắp xếp lịch làm việc cho nhân viên.</p></div><div className="branch-total"><FiGitBranch/><b>{branches.length}</b><span>chi nhánh</span></div></div><div className="branch-directory-tools"><label><FiSearch/><input value={branchSearch} onChange={e=>setBranchSearch(e.target.value)} placeholder="Tìm tên, mã hoặc địa chỉ chi nhánh"/></label></div>{error&&<div className="manager-form-error">{error}</div>}{branchesLoading?<div className="branch-card-grid">{[1,2].map(item=><i className="branch-card-skeleton" key={item}/>)}</div>:visibleBranches.length?<div className="branch-card-grid schedule-branch-grid">{visibleBranches.map(branch=><article className="branch-card schedule-branch-card" key={branch.branchId} onClick={()=>setSelectedBranch(branch)}><header><span><FiGitBranch/></span><div><h2>{branch.branchName}</h2><small>{branch.branchCode}</small></div><b className="branch-status">Đang hoạt động</b></header><div className="schedule-branch-summary"><span><FiUsers/><b>{branch.totalEmployees}</b><small>Nhân viên</small></span><span><b>{branch.workingEmployees}</b><small>Đang làm</small></span></div><footer><button type="button"><span>Xem lịch làm việc</span><FiArrowRight/></button></footer></article>)}</div>:<div className="card employee-table-empty">Không tìm thấy chi nhánh phù hợp</div>}</section>;

 return <section className="card list-card manager-schedule-page">
  <button className="schedule-branch-back" onClick={()=>{setSelectedBranch(null);setError("")}}><FiChevronLeft/> Tất cả chi nhánh</button>
  <div className="section-title"><div><span className="schedule-selected-branch"><FiGitBranch/>{selectedBranch.branchName}</span><h2>Lịch làm việc</h2><p>{view==="week"?`Tuần ${days[0].toLocaleDateString("vi-VN")} - ${days[6].toLocaleDateString("vi-VN")}`:`Tháng ${month.getMonth()+1}/${month.getFullYear()}`}</p></div><button className="btn btn-primary" onClick={openBuilder}><FiPlus/> Xếp lịch</button></div>
  <div className="manager-schedule-viewbar"><div className="schedule-tools manager-schedule-tools"><div><button className="icon-btn" onClick={()=>movePeriod(-1)}><FiChevronLeft/></button><button className="btn btn-light" onClick={goCurrent}>{view==="week"?"Tuần này":"Tháng này"}</button><button className="icon-btn" onClick={()=>movePeriod(1)}><FiChevronRight/></button></div></div><div className="manager-schedule-view-switch"><button className={view==="week"?"active":""} onClick={()=>switchView("week")}>Tuần</button><button className={view==="month"?"active":""} onClick={()=>switchView("month")}>Tháng</button></div><div className="manager-shift-legend">{["A","B","P1","P2","P3"].map(code=><span key={code}><i className={`code-${code.toLowerCase()}`}/>{code}</span>)}</div></div>
  <div className="manager-schedule-filters schedule-branch-filters"><label><FiSearch/><input placeholder="Tìm tên hoặc mã nhân viên" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></label><select value={filters.positionId} onChange={e=>setFilters({...filters,positionId:e.target.value})}><option value="">Tất cả vị trí</option>{positions.map(item=><option value={item.id} key={item.id}>{item.positionName}</option>)}</select></div>
  {error&&<div className="manager-form-error">{error}</div>}
  {loading?<div className="manager-schedule-loading"><i/><i/><i/></div>:view==="week"?(data.employees.length?<div className="table-wrap schedule-table manager-real-schedule"><table><thead><tr><th>Nhân viên</th>{days.map(date=><th key={dateKey(date)}>{dayNames[date.getDay()]}<small>{date.toLocaleDateString("vi-VN",{day:"2-digit",month:"2-digit"})}</small></th>)}</tr></thead><tbody>{data.employees.map(employee=><tr key={employee.employeeId}><td><b>{employee.fullName}</b><small>{employee.employeeCode} · {employee.positionName}</small></td>{days.map(date=>{const entries=scheduleMap[`${employee.employeeId}_${dateKey(date)}`]||[];return <td key={dateKey(date)}>{entries.length?entries.map(item=><div className={`manager-schedule-shift code-${String(item.shiftCode).toLowerCase()} status-${item.status}`} key={item.scheduleId}><b>{item.shiftCode} · {item.shiftName}</b><small>{item.startTime} - {item.endTime}</small><em>{statusLabels[item.status]||item.status}</em></div>):<span className="manager-unassigned">Chưa xếp</span>}</td>})}</tr>)}</tbody></table></div>:<div className="employee-table-empty">Chưa có nhân viên trong chi nhánh</div>):<><section className="manager-month-calendar"><div className="manager-month-weekdays">{weekNames.map((name,index)=><b className={index>4?"weekend":""} key={name}>{name}</b>)}</div><div className="manager-month-grid">{monthCells.map((date,index)=>date?<button key={dateKey(date)} className={`${selectedDate===dateKey(date)?"selected":""} ${dateKey(date)===dateKey(today)?"today":""}`} onClick={()=>setSelectedDate(dateKey(date))}><span>{date.getDate()}</span><small>{(schedulesByDate[dateKey(date)]||[]).length?`${(schedulesByDate[dateKey(date)]||[]).length} nhân viên`:"Chưa có lịch"}</small><i>{(schedulesByDate[dateKey(date)]||[]).slice(0,4).map(item=><em className={`code-${String(item.shiftCode).toLowerCase()}`} key={item.scheduleId}>{item.shiftCode}</em>)}</i></button>:<span className="blank" key={`blank-${index}`}/>)}</div></section><section className="manager-month-agenda"><header><div><FiCalendar/><span><b>{new Date(`${selectedDate}T00:00:00`).toLocaleDateString("vi-VN",{weekday:"long",day:"2-digit",month:"2-digit",year:"numeric"})}</b><small>{selectedSchedules.length} nhân viên có lịch</small></span></div></header>{selectedSchedules.length?<div className="manager-month-shifts">{selectedSchedules.map(item=>{const employee=employeesById.get(Number(item.employeeId));return <article key={item.scheduleId}><span className={`code-${String(item.shiftCode).toLowerCase()}`}>{item.shiftCode}</span><div><b>{employee?.fullName||"Nhân viên"}</b><small>{employee?.employeeCode} · {employee?.positionName}</small></div><p><FiClock/>{item.startTime} - {item.endTime}</p><em>{statusLabels[item.status]||item.status}</em></article>})}</div>:<div className="manager-month-empty">Ngày này chưa có nhân viên được xếp lịch.</div>}</section></>}
 </section>;
}
