import {useEffect,useMemo,useState} from "react";
import {Link,useParams} from "react-router-dom";
import {FiEdit3} from "react-icons/fi";
import {scheduleRegistrationApi} from "../../api/services";
const iso=v=>String(v||"").slice(0,10),dayNames=["CN","T2","T3","T4","T5","T6","T7"];
const range=(startValue,endValue)=>{const start=new Date(`${iso(startValue)}T00:00:00`),end=new Date(`${iso(endValue)}T00:00:00`),length=Math.floor((end-start)/864e5)+1;return Array.from({length},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})};
export default function ShiftRegistrationDetailPage(){const {periodId}=useParams(),[data,setData]=useState(null),[search,setSearch]=useState(""),[position,setPosition]=useState(""),[registered,setRegistered]=useState("");
 useEffect(()=>{scheduleRegistrationApi.detail(periodId).then(r=>setData(r.data))},[periodId]);
 const dates=useMemo(()=>data?range(data.period.weekStartDate,data.period.weekEndDate):[],[data]);
 const employees=useMemo(()=>{if(!data)return[];const map=new Map();data.rows.forEach(x=>{if(!map.has(x.employeeId))map.set(x.employeeId,{...x,registrations:{}});if(x.workDate)map.get(x.employeeId).registrations[iso(x.workDate)]=x.shiftCode});return [...map.values()].filter(x=>(!search||`${x.fullName} ${x.employeeCode}`.toLowerCase().includes(search.toLowerCase()))&&(!position||String(x.positionId)===position)&&(!registered||(registered==="yes")===(Object.keys(x.registrations).length>0)))},[data,search,position,registered]);
 if(!data)return <section className="card employee-table-empty">Đang tải bảng đăng ký...</section>;const positions=[...new Map(data.rows.map(x=>[String(x.positionId),x.positionName])).entries()];
 return <section className="card registration-sheet"><div className="section-title"><div><h2>{data.period.title}</h2><p>{data.period.branchName} · {data.period.registeredEmployees}/{data.period.totalEmployees} nhân viên đã đăng ký</p></div><Link className="btn btn-primary" to={`/manager/schedules/builder/${periodId}`}><FiEdit3/> Xếp lịch</Link></div><div className="registration-filters"><input placeholder="Tìm nhân viên..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={position} onChange={e=>setPosition(e.target.value)}><option value="">Tất cả vị trí</option>{positions.map(([id,name])=><option value={id} key={id}>{name}</option>)}</select><select value={registered} onChange={e=>setRegistered(e.target.value)}><option value="">Tất cả</option><option value="yes">Đã đăng ký</option><option value="no">Chưa đăng ký</option></select></div><div className="schedule-sheet-wrap"><table className="schedule-sheet"><thead><tr><th>Nhân viên</th>{dates.map(d=><th key={iso(d)}>{dayNames[d.getDay()]}<small>{d.toLocaleDateString("vi-VN",{day:"2-digit",month:"2-digit"})}</small></th>)}</tr></thead><tbody>{employees.map(e=><tr key={e.employeeId}><th><b>{e.fullName}</b><small>{e.employeeCode} · {e.positionName}</small></th>{dates.map(d=>{const code=e.registrations[iso(d)];return <td key={iso(d)}><span className={`sheet-shift shift-${(code||"rest").toLowerCase()}`}>{code||"—"}</span></td>})}</tr>)}</tbody></table></div><div className="shift-legend"><b>Full time:</b> A 08:00–16:00 · B 16:00–23:00 <b>Part time:</b> P1 08:00–12:00 · P2 12:00–17:00 · P3 17:00–23:00</div></section>}
