import { useEffect, useMemo, useState } from "react";
import { FiActivity, FiBarChart2, FiCalendar, FiChevronLeft, FiGitBranch, FiRefreshCw, FiTrendingDown, FiTrendingUp } from "react-icons/fi";
import { managerEmployeeApi, managerOperationApi } from "../../api/services";
import "../../styles/report-analytics.css";
import "../../styles/report-overview.css";
import "../../styles/report-comparison.css";
import "../../styles/report-date-picker.css";
import OperationalReports from "./OperationalReports";
import { vietnamToday } from "../../utils/vietnamTime";
import VietnamDateInput from "../../components/VietnamDateInput";

const money = value => `${Number(value || 0).toLocaleString("vi-VN")}đ`;
const total = (items, field = "totalRevenue") => items.reduce((sum, item) => sum + Number(item[field] || 0), 0);
const growth = (now, before) => before ? ((now - before) / before) * 100 : now ? 100 : 0;
const monthLabel = month => { const [year, value] = month.split("-"); return `Tháng ${Number(value)}/${year}`; };
const monthBounds = month => { const [year, number] = month.split("-").map(Number); return { from: `${month}-01`, to: `${month}-${String(new Date(year, number, 0).getDate()).padStart(2, "0")}` }; };
const yearBounds = year => ({ from: `${year}-01-01`, to: `${year}-12-31` });
const previousMonth = month => { const [year, number] = month.split("-").map(Number), date = new Date(year, number - 2, 1); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; };
const percent = value => `${Math.abs(Number(value || 0)).toLocaleString("vi-VN", { maximumFractionDigits: 1 })}%`;

function GrowthBadge({ value }) { return <span className={value < 0 ? "comparison-negative" : "comparison-positive"}>{value < 0 ? <FiTrendingDown /> : <FiTrendingUp />}{percent(value)}</span>; }

function GrowthChart({ branches, items, year }) {
  const colors = ["#f5b800", "#1f7ae0", "#16a36a", "#e05f38", "#8a5adf", "#252525"];
  const series = branches.map((branch, index) => ({ branch, color: colors[index % colors.length], values: Array.from({ length: 12 }, (_, monthIndex) => total(items.filter(item => String(item.branchId) === String(branch.id) && Number(String(item.businessDate).slice(5, 7)) === monthIndex + 1))) }));
  const max = Math.max(...series.flatMap(row => row.values), 1);
  const points = values => values.map((value, index) => `${35 + index * 75},${205 - value / max * 165}`).join(" ");
  return <section className="card annual-growth-card"><header><div><small>BIỂU ĐỒ TĂNG TRƯỞNG</small><h2>Doanh thu 12 tháng năm {year}</h2><p>So sánh xu hướng doanh thu giữa các cửa hàng.</p></div><FiActivity /></header>
    <div className="growth-chart-scroll"><svg viewBox="0 0 900 245" role="img" aria-label={`Biểu đồ doanh thu năm ${year}`}><g className="growth-grid">{[40,95,150,205].map(y=><line key={y} x1="35" y1={y} x2="860" y2={y}/>)}</g>{series.map(row=><g key={row.branch.id}><polyline points={points(row.values)} style={{stroke:row.color}}/>{row.values.map((value,index)=><circle key={index} cx={35+index*75} cy={205-value/max*165} r="4" style={{fill:row.color}}><title>{row.branch.branchName}: {money(value)}</title></circle>)}</g>)}{Array.from({length:12},(_,index)=><text key={index} x={35+index*75} y="232" textAnchor="middle">T{index+1}</text>)}</svg></div>
    <div className="growth-legend">{series.map(row=><span key={row.branch.id}><i style={{background:row.color}}/>{row.branch.branchName}</span>)}</div>
  </section>;
}

function MonthlyComparisonChart({ rows, month, previous }) {
  const max = Math.max(...rows.flatMap(row => [row.revenue, row.previousRevenue]), 1);
  return <section className="card annual-growth-card"><header><div><small>BIỂU ĐỒ SO SÁNH THÁNG</small><h2>{monthLabel(previous)} và {monthLabel(month)}</h2><p>Đối chiếu doanh thu giữa các chi nhánh trong hai tháng liền nhau.</p></div><FiBarChart2 /></header>
    <div style={{display:"grid",gap:14,marginTop:22}}>{rows.map(row=><div key={row.id} style={{display:"grid",gridTemplateColumns:"minmax(120px,220px) 1fr",gap:15,alignItems:"center"}}><b>{row.branchName}</b><div style={{display:"grid",gap:7}}><div style={{display:"flex",alignItems:"center",gap:9}}><small style={{width:75}}>{monthLabel(previous)}</small><i style={{display:"block",height:14,width:`${Math.max(2,row.previousRevenue/max*100)}%`,background:"#d9d9d9",borderRadius:8}}/><strong>{money(row.previousRevenue)}</strong></div><div style={{display:"flex",alignItems:"center",gap:9}}><small style={{width:75}}>{monthLabel(month)}</small><i style={{display:"block",height:14,width:`${Math.max(2,row.revenue/max*100)}%`,background:"#f5b800",borderRadius:8}}/><strong>{money(row.revenue)}</strong></div></div></div>)}</div>
  </section>;
}

function RevenueReportsPage() {
  const [reportDate, setReportDate] = useState("2026-08-01"), month = reportDate.slice(0, 7), year = Number(month.slice(0, 4));
  const [branches, setBranches] = useState([]), [branchId, setBranchId] = useState("");
  const [compareMode, setCompareMode] = useState("month"), [comparisonBranchId, setComparisonBranchId] = useState("");
  const [current, setCurrent] = useState([]), [previous, setPrevious] = useState([]), [annual, setAnnual] = useState([]), [priorAnnual, setPriorAnnual] = useState([]);
  const [loading, setLoading] = useState(true), [error, setError] = useState("");
  async function load() { try { setLoading(true); setError(""); const responses = await Promise.all([managerOperationApi.report("monthly", monthBounds(month)), managerOperationApi.report("monthly", monthBounds(previousMonth(month))), managerOperationApi.report("monthly", yearBounds(year)), managerOperationApi.report("monthly", yearBounds(year - 1))]); setCurrent(responses[0].data?.items || []); setPrevious(responses[1].data?.items || []); setAnnual(responses[2].data?.items || []); setPriorAnnual(responses[3].data?.items || []); } catch (e) { setError(e.response?.data?.message || "Không tải được dữ liệu báo cáo ca"); } finally { setLoading(false); } }
  useEffect(() => { managerEmployeeApi.branches().then(response => setBranches(response.data || [])).catch(() => {}); }, []);
  useEffect(() => { load(); }, [month]);
  const branchRows = useMemo(() => branches.map(branch => { const filter = list => list.filter(x => String(x.branchId) === String(branch.id)), items = filter(current), oldItems = filter(previous), yearItems = filter(annual), oldYearItems = filter(priorAnnual), revenue = total(items), previousRevenue = total(oldItems), yearRevenue = total(yearItems), previousYearRevenue = total(oldYearItems); return { ...branch, items, revenue, previousRevenue, yearRevenue, previousYearRevenue, monthGrowth:growth(revenue,previousRevenue), yearGrowth:growth(yearRevenue,previousYearRevenue) }; }), [branches,current,previous,annual,priorAnnual]);
  const comparisonRows = comparisonBranchId ? branchRows.filter(branch => String(branch.id) === String(comparisonBranchId)) : branchRows;
  const comparisonBranches = comparisonBranchId ? branches.filter(branch => String(branch.id) === String(comparisonBranchId)) : branches;
  const comparisonAnnual = comparisonBranchId ? annual.filter(item => String(item.branchId) === String(comparisonBranchId)) : annual;
  const selectedBranch = branches.find(branch => String(branch.id) === String(branchId));
  const visible = branchId ? current.filter(x => String(x.branchId) === String(branchId)) : current, visiblePrevious = branchId ? previous.filter(x => String(x.branchId) === String(branchId)) : previous;
  const revenue = total(visible), oldRevenue = total(visiblePrevious), monthGrowth = growth(revenue, oldRevenue);
  const paymentTotal = ["cashRevenue","beRevenue","grabRevenue","shopeefoodRevenue","mposRevenue","xanhSmRevenue"].reduce((result,key)=>({...result,[key]:total(visible,key)}),{});
  const days = useMemo(()=>{const grouped={};visible.forEach(item=>{grouped[item.businessDate]=(grouped[item.businessDate]||0)+Number(item.totalRevenue||0)});return Object.entries(grouped).sort(([a],[b])=>a.localeCompare(b))},[visible]);
  const maxDay=Math.max(...days.map(([,value])=>value),1), annualRevenue=total(annual), priorAnnualRevenue=total(priorAnnual), annualGrowth=growth(annualRevenue,priorAnnualRevenue);
  return <div className={`shift-analytics ${branchId?"branch-detail":"branch-overview"}`}>
    <section className="card shift-analytics-head"><div>{branchId&&<button className="shift-back" onClick={()=>setBranchId("")}><FiChevronLeft/> Tất cả chi nhánh</button>}<h1>{branchId?`Báo cáo — ${selectedBranch?.branchName}`:"Báo cáo doanh thu"}</h1><p>Thống kê trực tiếp từ các báo cáo ca đã kết và gửi lên hệ thống.</p></div><div className="shift-report-controls"><label>Ngày thuộc tháng xem<VietnamDateInput value={reportDate} onChange={event=>event.target.value&&setReportDate(event.target.value)}/></label><button type="button" className="report-current-date" onClick={()=>setReportDate(vietnamToday())}><FiCalendar/> Hiện tại</button>{!branchId&&<><label>Kiểu so sánh<select value={compareMode} onChange={event=>setCompareMode(event.target.value)} style={{height:40,padding:"0 12px",border:"1px solid #e5e5e5",borderRadius:9,minWidth:150}}><option value="month">So sánh tháng</option><option value="year">So sánh năm</option></select></label><label>Chi nhánh<select value={comparisonBranchId} onChange={event=>setComparisonBranchId(event.target.value)} style={{height:40,padding:"0 12px",border:"1px solid #e5e5e5",borderRadius:9,minWidth:190}}><option value="">Tất cả chi nhánh</option>{branches.map(branch=><option key={branch.id} value={branch.id}>{branch.branchName}</option>)}</select></label></>}<button className="btn btn-light" onClick={load}><FiRefreshCw/> Tải lại</button></div></section>
    {error&&<div className="manager-form-error">{error}</div>}{loading?<section className="card shift-report-empty">Đang tải báo cáo...</section>:<>
      {!branchId&&<>
        <section className="shift-report-stats"><article className="card"><small>Doanh thu {monthLabel(month)}</small><b>{money(revenue)}</b></article><article className="card"><small>{monthLabel(previousMonth(month))}</small><b>{money(oldRevenue)}</b></article><article className={`card ${monthGrowth<0?"down":"up"}`}><small>So với tháng trước</small><b>{monthGrowth<0?<FiTrendingDown/>:<FiTrendingUp/>}{percent(monthGrowth)}</b></article><article className="card"><small>Số báo cáo ca</small><b>{visible.length}</b></article></section>
        <section className="card branch-comparison"><header><div><h2>So sánh các cửa hàng</h2><p>Doanh thu và tăng trưởng của từng chi nhánh trong tháng đang xem.</p></div><FiGitBranch/></header><div className="branch-comparison-grid">{branchRows.map(branch=><article key={branch.id}><div className="branch-comparison-name"><span><FiGitBranch/></span><div><b>{branch.branchName}</b><small>{branch.branchCode}</small></div></div><strong>{money(branch.revenue)}</strong><p>Tháng trước: {money(branch.previousRevenue)}</p><GrowthBadge value={branch.monthGrowth}/><button onClick={()=>setBranchId(String(branch.id))}>Xem chi tiết chi nhánh</button></article>)}</div></section>
        <section className="comparison-section-title"><small>PHÂN TÍCH MỞ RỘNG</small><h2>So sánh tăng trưởng theo tháng và năm</h2><p>Phần thống kê chuyên sâu được bổ sung bên dưới giao diện báo cáo hiện tại.</p></section>
        {compareMode==="year"&&<section className="comparison-hero-stats"><article><small>Tổng doanh thu {year}</small><b>{money(total(comparisonAnnual))}</b><GrowthBadge value={growth(total(comparisonAnnual),total(comparisonBranchId?priorAnnual.filter(item=>String(item.branchId)===String(comparisonBranchId)):priorAnnual))}/></article><article><small>Tổng doanh thu {year-1}</small><b>{money(total(comparisonBranchId?priorAnnual.filter(item=>String(item.branchId)===String(comparisonBranchId)):priorAnnual))}</b><em>Năm đối chiếu</em></article><article><small>Chi nhánh dẫn đầu</small><b>{[...comparisonRows].sort((a,b)=>b.yearRevenue-a.yearRevenue)[0]?.branchName||"Chưa có"}</b><em>{money(Math.max(...comparisonRows.map(x=>x.yearRevenue),0))}</em></article><article><small>Tổng báo cáo ca</small><b>{comparisonAnnual.length}</b><em>Trong năm {year}</em></article></section>}
        {compareMode==="year"?<GrowthChart branches={comparisonBranches} items={comparisonAnnual} year={year}/>:<MonthlyComparisonChart rows={comparisonRows} month={month} previous={previousMonth(month)}/>}
      </>}
      {branchId&&<><div className="shift-selected-branch"><FiGitBranch/>{selectedBranch?.branchName}</div><section className="shift-report-stats"><article className="card"><small>Doanh thu {monthLabel(month)}</small><b>{money(revenue)}</b></article><article className="card"><small>{monthLabel(previousMonth(month))}</small><b>{money(oldRevenue)}</b></article><article className={`card ${monthGrowth<0?"down":"up"}`}><small>So với tháng trước</small><b>{monthGrowth<0?<FiTrendingDown/>:<FiTrendingUp/>}{percent(monthGrowth)}</b></article><article className="card"><small>Số báo cáo ca</small><b>{visible.length}</b></article></section><section className="shift-report-charts"><article className="card"><header><h2>Doanh thu theo ngày</h2><small>{monthLabel(month)}</small></header>{days.length?<div className="daily-revenue-bars">{days.map(([date,value])=><div key={date}><span title={money(value)} style={{height:`${Math.max(8,value/maxDay*100)}%`}}/><b>{money(value)}</b><small>{date.slice(8,10)}/{date.slice(5,7)}</small></div>)}</div>:<div className="shift-report-empty">Tháng này chưa có báo cáo ca.</div>}</article><article className="card"><header><h2>Doanh thu theo kênh</h2><small>Tổng hợp từ báo cáo ca</small></header><div className="payment-comparison">{[["Tiền mặt","cashRevenue"],["Be","beRevenue"],["Grab","grabRevenue"],["ShopeeFood","shopeefoodRevenue"],["MPOS","mposRevenue"],["Xanh SM","xanhSmRevenue"]].map(([label,key])=><div key={key}><span>{label}</span><b>{money(paymentTotal[key])}</b><i><em style={{width:`${revenue?Number(paymentTotal[key])/revenue*100:0}%`}}/></i></div>)}</div></article></section></>}
      <section className="card report-month-table comparison-table"><header><div><small>BẢNG THỐNG KÊ TỔNG HỢP</small><h2>{compareMode==="month"?"So sánh chi nhánh theo tháng":"So sánh chi nhánh theo năm"}</h2></div><FiBarChart2/></header><div className="table-wrap"><table><thead>{compareMode==="month"?<tr><th>Chi nhánh</th><th>{monthLabel(month)}</th><th>{monthLabel(previousMonth(month))}</th><th>Chênh lệch</th><th>Tăng trưởng</th><th>Số ca</th><th></th></tr>:<tr><th>Chi nhánh</th><th>Năm {year}</th><th>Năm {year-1}</th><th>Chênh lệch</th><th>Tăng trưởng</th><th>Số ca</th><th></th></tr>}</thead><tbody>{comparisonRows.map(branch=>compareMode==="month"?<tr key={branch.id}><td><b>{branch.branchName}</b><small>{branch.branchCode}</small></td><td><strong>{money(branch.revenue)}</strong></td><td>{money(branch.previousRevenue)}</td><td>{money(branch.revenue-branch.previousRevenue)}</td><td><GrowthBadge value={branch.monthGrowth}/></td><td>{branch.items.length}</td><td><button onClick={()=>setBranchId(String(branch.id))}>Chi tiết</button></td></tr>:<tr key={branch.id}><td><b>{branch.branchName}</b><small>{branch.branchCode}</small></td><td><strong>{money(branch.yearRevenue)}</strong></td><td>{money(branch.previousYearRevenue)}</td><td>{money(branch.yearRevenue-branch.previousYearRevenue)}</td><td><GrowthBadge value={branch.yearGrowth}/></td><td>{branch.items.length}</td><td><button onClick={()=>setBranchId(String(branch.id))}>Chi tiết</button></td></tr>)}</tbody></table></div></section>
    </>}
  </div>;
}

export default function ReportsPage(){
  const [tab,setTab]=useState('REVENUE');
  return <><nav className="report-type-tabs"><button className={tab==='REVENUE'?'active':''} onClick={()=>setTab('REVENUE')}>Doanh thu</button><button className={tab==='HYGIENE'?'active':''} onClick={()=>setTab('HYGIENE')}>Vệ sinh</button><button className={tab==='GOODS'?'active':''} onClick={()=>setTab('GOODS')}>Hàng hóa</button></nav>{tab==='REVENUE'?<RevenueReportsPage/>:<OperationalReports type={tab}/>}</>;
}
