import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {FiCalendar,FiEye,FiLock,FiPlus,FiSend,FiTrash2,FiUnlock} from "react-icons/fi";
import {managerEmployeeApi,scheduleRegistrationApi} from "../../api/services";
const labels={draft:"Nháp",open:"Đang mở",locked:"Đã khóa",published:"Đã công bố",cancelled:"Đã hủy"};
const iso=v=>String(v||"").slice(0,10),localIso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`,dt=v=>v?new Date(v).toLocaleString("vi-VN"):"—";
const nextMonday=()=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()+((8-d.getDay())%7||7));return localIso(d)};
const initial=()=>({branchId:"",title:"Đăng ký lịch làm tuần mới",weekStartDate:nextMonday(),weekEndDate:"",registrationOpenAt:"",registrationCloseAt:"",note:""});
export default function ShiftRegistrationPage(){const [items,setItems]=useState([]),[branches,setBranches]=useState([]),[show,setShow]=useState(false),[form,setForm]=useState(initial),[message,setMessage]=useState(""),[error,setError]=useState("");
 const load=()=>scheduleRegistrationApi.periods().then(r=>setItems(r.data)).catch(e=>setError(e.response?.data?.message||"Không tải được dữ liệu"));
 useEffect(()=>{load();managerEmployeeApi.branches().then(r=>setBranches(r.data))},[]);
 async function create(e){e.preventDefault();setError("");if(new Date(`${form.weekEndDate}T00:00:00`)<new Date(`${form.weekStartDate}T00:00:00`))return setError("Ngày kết thúc phải bằng hoặc sau ngày bắt đầu");if(new Date(form.registrationOpenAt)>=new Date(form.registrationCloseAt))return setError("Thời gian đóng đăng ký phải sau thời gian mở");if(new Date(form.registrationCloseAt)>new Date(`${form.weekStartDate}T23:59:59`))return setError("Thời gian đóng đăng ký phải trước hoặc bằng ngày bắt đầu");const withSeconds=value=>value&&value.length===16?`${value}:00`:value;try{const r=await scheduleRegistrationApi.create({...form,branchId:Number(form.branchId),registrationOpenAt:withSeconds(form.registrationOpenAt),registrationCloseAt:withSeconds(form.registrationCloseAt)});setMessage(r.message);setShow(false);setForm(initial());load()}catch(x){setError(x.response?.data?.message||"Không thể tạo đợt")}}
 async function action(item,name){if(name==="lock"&&!window.confirm("Sau khi khóa, nhân viên sẽ không thể thay đổi đăng ký. Bạn có chắc chắn không?"))return;if(name==="publish"&&!window.confirm("Công bố lịch chính thức cho toàn bộ nhân viên?"))return;setMessage("");setError("");try{const r=await scheduleRegistrationApi.action(item.periodId,name);setMessage(r.message);load()}catch(x){setError(x.response?.data?.message||"Thao tác thất bại")}}
 async function remove(item){if(!window.confirm(`Xóa đợt “${item.title}”? Lịch chính thức đã công bố (nếu có) vẫn được giữ nguyên.`))return;setMessage("");setError("");try{const r=await scheduleRegistrationApi.remove(item.periodId);setMessage(r.message);load()}catch(x){setError(x.response?.data?.message||"Không thể xóa đợt đăng ký")}}
 return <section className="card list-card registration-manager"><div className="section-title"><div><h2>Đăng ký ca</h2><p>Mở đợt, tổng hợp nguyện vọng và công bố lịch theo tuần.</p></div><button className="btn btn-primary" onClick={()=>setShow(true)}><FiPlus/> Tạo đợt đăng ký</button></div>{message&&<div className="manager-form-success">{message}</div>}{error&&<div className="manager-form-error">{error}</div>}
 <div className="registration-period-table"><table><thead><tr><th>Tên đợt</th><th>Chi nhánh</th><th>Tuần làm việc</th><th>Thời gian đăng ký</th><th>Tiến độ</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{items.map(x=><tr key={x.periodId}><td><b>{x.title}</b></td><td>{x.branchName}</td><td>{iso(x.weekStartDate).split("-").reverse().join("/")} – {iso(x.weekEndDate).split("-").reverse().join("/")}</td><td><small>{dt(x.registrationOpenAt)}<br/>đến {dt(x.registrationCloseAt)}</small></td><td>{x.registeredEmployees}/{x.totalEmployees} nhân viên</td><td><span className={`status registration-${x.status}`}>{labels[x.status]}</span></td><td><div className="employee-actions"><Link title="Xem đăng ký" to={`/manager/shift-registration/${x.periodId}`}><FiEye/></Link>{x.status==="open"?<button title="Khóa đăng ký" onClick={()=>action(x,"lock")}><FiLock/></button>:<button title="Mở đăng ký" onClick={()=>action(x,"open")}><FiUnlock/></button>}{["locked","published"].includes(x.status)&&<Link title="Xếp lịch" to={`/manager/schedules/builder/${x.periodId}`}><FiCalendar/></Link>}{x.status==="locked"&&<button title="Công bố" onClick={()=>action(x,"publish")}><FiSend/></button>}<button className="danger" title="Xóa đợt" onClick={()=>remove(x)}><FiTrash2/></button></div></td></tr>)}</tbody></table></div>{!items.length&&<div className="employee-table-empty">Chưa có đợt đăng ký</div>}
 {show&&<div className="manager-modal-backdrop"><form className="employee-modal registration-form" onSubmit={create}><header><div><h2>Tạo đợt đăng ký ca</h2><p>Chọn khoảng ngày phù hợp với kỳ chốt lương thực tế.</p></div><button type="button" onClick={()=>setShow(false)}>×</button></header><fieldset><section><div className="employee-form-grid"><label>Chi nhánh *<select required value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}><option value="">Chọn chi nhánh</option>{branches.map(x=><option key={x.id} value={x.id}>{x.branchName}</option>)}</select></label><label>Tên đợt *<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Ngày bắt đầu *<input required type="date" value={form.weekStartDate} onChange={e=>setForm({...form,weekStartDate:e.target.value})}/></label><label>Ngày kết thúc *<input required type="date" min={form.weekStartDate} value={form.weekEndDate} onChange={e=>setForm({...form,weekEndDate:e.target.value})}/></label><label>Mở đăng ký lúc *<input required type="datetime-local" value={form.registrationOpenAt} onChange={e=>setForm({...form,registrationOpenAt:e.target.value})}/></label><label>Đóng đăng ký lúc *<input required type="datetime-local" value={form.registrationCloseAt} onChange={e=>setForm({...form,registrationCloseAt:e.target.value})}/></label><label>Ghi chú<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></div></section></fieldset><footer><button type="button" className="btn btn-light" onClick={()=>setShow(false)}>Hủy</button><button className="btn btn-primary">Tạo đợt</button></footer></form></div>}</section>}
