import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {FiAlertTriangle,FiCalendar,FiChevronDown,FiChevronUp,FiEye,FiLock,FiPlus,FiSend,FiTrash2,FiUnlock,FiX} from "react-icons/fi";
import {managerEmployeeApi,scheduleRegistrationApi} from "../../api/services";
const labels={draft:"Nháp",open:"Đang mở",locked:"Đã khóa",published:"Đã công bố",cancelled:"Đã hủy"};
const iso=v=>String(v||"").slice(0,10),localIso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`,dt=v=>v?new Date(v).toLocaleString("vi-VN"):"—";
const scheduleTestMode=import.meta.env.VITE_APP_ENV==="sandbox"&&String(import.meta.env.VITE_SCHEDULE_TEST_MODE).toLowerCase()==="true";
const initial=()=>({branchId:"",title:"",startDate:"",endDate:"",registrationOpenAt:"",registrationCloseAt:"",note:""});
const autoTitle=(start,end)=>start&&end?`Đăng ký lịch ${start.slice(8,10)}/${start.slice(5,7)} - ${end.slice(8,10)}/${end.slice(5,7)}`:"Tên đợt sẽ được tạo tự động";
const localDateTime=value=>{const pad=x=>String(x).padStart(2,"0");return `${value.getFullYear()}-${pad(value.getMonth()+1)}-${pad(value.getDate())}T${pad(value.getHours())}:${pad(value.getMinutes())}`};
export default function ShiftRegistrationPage(){const [items,setItems]=useState([]),[branches,setBranches]=useState([]),[show,setShow]=useState(false),[advanced,setAdvanced]=useState(false),[form,setForm]=useState(initial),[message,setMessage]=useState(""),[error,setError]=useState(""),[confirm,setConfirm]=useState(null),[confirming,setConfirming]=useState(false);
 const load=()=>scheduleRegistrationApi.periods().then(r=>setItems(r.data)).catch(e=>setError(e.response?.data?.message||"Không tải được dữ liệu"));
 useEffect(()=>{load();managerEmployeeApi.branches().then(r=>setBranches(r.data))},[]);
 function toggleAdvanced(){setAdvanced(value=>{if(!value&&!form.registrationOpenAt){const now=new Date(),close=form.startDate?new Date(`${form.startDate}T00:00:00`):null;if(close)close.setMinutes(-1);setForm(current=>({...current,registrationOpenAt:localDateTime(now),registrationCloseAt:close?localDateTime(close):""}))}return !value})}
 async function create(e){e.preventDefault();setError("");if(!form.branchId)return setError("Vui lòng chọn chi nhánh.");if(!form.startDate)return setError("Vui lòng chọn ngày bắt đầu.");if(!form.endDate)return setError("Vui lòng chọn ngày kết thúc.");if(form.endDate<form.startDate)return setError("Ngày kết thúc phải từ ngày bắt đầu trở đi.");if(!scheduleTestMode&&form.startDate<localIso(new Date()))return setError("Không thể tạo đợt có ngày bắt đầu trong quá khứ.");const withSeconds=value=>value&&value.length===16?`${value}:00`:value;const payload={branchId:Number(form.branchId),startDate:form.startDate,endDate:form.endDate,note:form.note};if(advanced)Object.assign(payload,{title:form.title,registrationOpenAt:withSeconds(form.registrationOpenAt),registrationCloseAt:withSeconds(form.registrationCloseAt)});try{const r=await scheduleRegistrationApi.create(payload);setMessage(r.message||"Đã tạo và mở đợt đăng ký lịch.");setShow(false);setAdvanced(false);setForm(initial());load()}catch(x){setError(x.response?.data?.message||"Không thể tạo đợt đăng ký")}}
 async function action(item,name){setMessage("");setError("");try{const r=await scheduleRegistrationApi.action(item.periodId,name);setMessage(r.message);load()}catch(x){setError(x.response?.data?.message||"Thao tác thất bại")}}
 async function remove(item){setMessage("");setError("");try{const r=await scheduleRegistrationApi.remove(item.periodId);setMessage(r.message);load()}catch(x){setError(x.response?.data?.message||"Không thể xóa đợt đăng ký")}}
 function ask(item,type){const content={lock:{title:"Khóa đăng ký ca?",description:"Sau khi khóa, nhân viên sẽ không thể thêm hoặc thay đổi nguyện vọng đăng ký trong đợt này.",confirmText:"Khóa đăng ký"},publish:{title:"Công bố lịch chính thức?",description:"Lịch sẽ được gửi đến toàn bộ nhân viên thuộc đợt đăng ký và xuất hiện trong lịch làm việc.",confirmText:"Công bố lịch"},remove:{title:"Xóa đợt đăng ký?",description:"Đợt đăng ký và các nguyện vọng liên quan sẽ bị xóa. Lịch chính thức đã công bố vẫn được giữ nguyên.",confirmText:"Xóa đợt"}}[type];setConfirm({...content,item,type})}
 async function confirmAction(){if(!confirm||confirming)return;setConfirming(true);try{if(confirm.type==="remove")await remove(confirm.item);else await action(confirm.item,confirm.type);setConfirm(null)}finally{setConfirming(false)}}
 return <section className="card list-card registration-manager">{scheduleTestMode&&<div className="schedule-test-banner">Chế độ kiểm thử: đang cho phép dùng ngày quá khứ</div>}<div className="section-title"><div><h2>Đăng ký ca</h2><p>Mở đợt, tổng hợp nguyện vọng và công bố lịch theo khoảng ngày.</p></div><button className="btn btn-primary" onClick={()=>setShow(true)}><FiPlus/> {scheduleTestMode?"Tạo đợt kiểm thử":"Tạo đợt đăng ký"}</button></div>{message&&<div className="manager-form-success">{message}</div>}{error&&!show&&<div className="manager-form-error">{error}</div>}
 <div className="registration-period-table"><table><thead><tr><th>Tên đợt</th><th>Chi nhánh</th><th>Khoảng ngày làm việc</th><th>Hạn đăng ký</th><th>Tiến độ</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{items.map(x=><tr key={x.periodId}><td><b>{x.title}</b></td><td>{x.branchName}</td><td>{iso(x.weekStartDate).split("-").reverse().join("/")} – {iso(x.weekEndDate).split("-").reverse().join("/")}</td><td><small>{dt(x.registrationCloseAt)}</small></td><td>{x.registeredEmployees}/{x.totalEmployees} nhân viên</td><td><span className={`status registration-${x.status}`}>{labels[x.status]}</span></td><td><div className="employee-actions"><Link title="Xem đăng ký" to={`/manager/shift-registration/${x.periodId}`}><FiEye/></Link>{x.status==="open"?<button title="Đang mở — bấm để khóa đăng ký" onClick={()=>ask(x,"lock")}><FiUnlock/></button>:<button title="Đã khóa — bấm để mở đăng ký" onClick={()=>action(x,"open")}><FiLock/></button>}{["locked","published"].includes(x.status)&&<Link title="Xếp lịch" to={`/manager/schedules/builder/${x.periodId}`}><FiCalendar/></Link>}{x.status==="locked"&&<button title="Công bố" onClick={()=>ask(x,"publish")}><FiSend/></button>}<button className="danger" title="Xóa đợt" onClick={()=>ask(x,"remove")}><FiTrash2/></button></div></td></tr>)}</tbody></table></div>{!items.length&&<div className="employee-table-empty">Chưa có đợt đăng ký</div>}
 {confirm&&<div className="manager-modal-backdrop registration-confirm-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!confirming)setConfirm(null)}}><div className={`registration-confirm-modal ${confirm.type==="remove"?"danger":""}`} role="dialog" aria-modal="true" aria-labelledby="registration-confirm-title"><button className="registration-confirm-close" type="button" aria-label="Đóng" disabled={confirming} onClick={()=>setConfirm(null)}><FiX/></button><div className="registration-confirm-icon">{confirm.type==="remove"?<FiTrash2/>:<FiAlertTriangle/>}</div><h2 id="registration-confirm-title">{confirm.title}</h2><p>{confirm.description}</p><div className="registration-confirm-period"><span>Đợt đăng ký</span><b>{confirm.item.title}</b><small>{confirm.item.branchName} · {iso(confirm.item.weekStartDate).split("-").reverse().join("/")} – {iso(confirm.item.weekEndDate).split("-").reverse().join("/")}</small></div><div className="registration-confirm-actions"><button type="button" className="btn btn-light" disabled={confirming} onClick={()=>setConfirm(null)}>Hủy</button><button type="button" className={`btn ${confirm.type==="remove"?"btn-danger":"btn-primary"}`} disabled={confirming} onClick={confirmAction}>{confirming?"Đang xử lý...":confirm.confirmText}</button></div></div></div>}
 {show&&<div className="manager-modal-backdrop"><form className="employee-modal registration-form simplified-registration-form" onSubmit={create}><header><div><h2>{scheduleTestMode?"Tạo đợt kiểm thử":"Tạo đợt đăng ký"}</h2><p>Chọn khoảng ngày làm việc, hệ thống sẽ tự mở đăng ký cho nhân viên.</p></div><button type="button" onClick={()=>{setShow(false);setError("")}}>×</button></header><fieldset><section>{scheduleTestMode&&<div className="schedule-test-banner">Chế độ kiểm thử: đang cho phép dùng ngày quá khứ</div>}{error&&<div className="manager-form-error">{error}</div>}<div className="registration-basic-fields"><label>Chi nhánh *<select required value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}><option value="">Chọn chi nhánh</option>{branches.map(x=><option key={x.id} value={x.id}>{x.branchName}</option>)}</select></label><div className="registration-date-row"><label>Ngày bắt đầu làm việc *<input required type="date" min={scheduleTestMode?undefined:localIso(new Date())} value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value,registrationCloseAt:""})}/></label><label>Ngày kết thúc làm việc *<input required type="date" min={form.startDate} value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label></div><label>Ghi chú <small>Không bắt buộc</small><textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Ghi chú dành cho nhân viên hoặc quản lý"/></label></div><div className="registration-auto-name">{autoTitle(form.startDate,form.endDate)}</div><button type="button" className="registration-advanced-toggle" onClick={toggleAdvanced}>{advanced?<FiChevronUp/>:<FiChevronDown/>} Tùy chỉnh thời gian đăng ký</button>{advanced&&<div className="registration-advanced-fields"><label>Mở đăng ký lúc *<input required type="datetime-local" value={form.registrationOpenAt} onChange={e=>setForm({...form,registrationOpenAt:e.target.value})}/></label><label>Đóng đăng ký lúc *<input required type="datetime-local" value={form.registrationCloseAt} onChange={e=>setForm({...form,registrationCloseAt:e.target.value})}/></label><label>Tên đợt<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder={autoTitle(form.startDate,form.endDate)}/></label></div>}</section></fieldset><footer><button type="button" className="btn btn-light" onClick={()=>{setShow(false);setError("")}}>Hủy</button><button className="btn btn-primary">{scheduleTestMode?"Tạo đợt kiểm thử":"Tạo và mở đăng ký"}</button></footer></form></div>}</section>}
