import {useEffect,useMemo,useState} from "react";
import {Link,useOutletContext} from "react-router-dom";
import {FiBell,FiCalendar,FiClipboard,FiClock,FiDollarSign,FiFileText,FiLogOut,FiRefreshCw,FiPlusCircle} from "react-icons/fi";
import {employeeApi} from "../../api/services";
import {dateKey,shortDate,time} from "../../utils/employeeFormat";
const actions=[["/employee/payroll","Lương của tôi",FiDollarSign],["/employee/shift-registration","Đăng ký lịch làm",FiPlusCircle],["/employee/schedule","Lịch làm",FiCalendar],["/employee/attendance","Chấm công",FiClock],["/employee/shift","Mở ca",FiRefreshCw],["/employee/shift-closing","Đóng ca",FiLogOut],["/employee/shift-report","Báo cáo ca",FiFileText],["/employee/expenses","Chi phí",FiDollarSign],["/employee/leave-request","Xin nghỉ",FiClipboard],["/employee/notifications","Thông báo",FiBell]];
export default function EmployeeHomePage(){const {profile}=useOutletContext(),[shift,setShift]=useState(null),[schedules,setSchedules]=useState([]),[notices,setNotices]=useState([]),[registration,setRegistration]=useState(null),[error,setError]=useState("");
 useEffect(()=>{const now=new Date(),from=new Date(now);from.setDate(now.getDate()-((now.getDay()+6)%7));const to=new Date(from);to.setDate(from.getDate()+6);Promise.all([employeeApi.attendanceToday(),employeeApi.schedules(dateKey(from),dateKey(to)),employeeApi.notifications(),employeeApi.currentShiftRegistration()]).then(([a,b,c,d])=>{setShift(a.data?.schedule?{...a.data.schedule,...a.data.employee,attendance:a.data.attendance}:null);setSchedules(b.data||[]);setNotices((c.data||[]).slice(0,3));setRegistration(d.data)}).catch(e=>setError(e.response?.data?.message||"Không tải được dữ liệu"))},[]);
 const hours=useMemo(()=>schedules.reduce((sum,x)=>{const [sh,sm]=time(x.startTime).split(":").map(Number),[eh,em]=time(x.endTime).split(":").map(Number);return sum+Math.max(0,(eh*60+em-sh*60-sm)/60)},0),[schedules]);
 return <div>{error&&<div className="emp-error">{error}</div>}<section className="emp-card emp-shift-card"><span className={`emp-badge ${shift?.attendance?"success":"warn"}`}>{shift?.attendance?.status==="completed"?"Đã hoàn thành":shift?.attendance?"Đang làm việc":shift?"Chưa chấm công":"Chưa có lịch hôm nay"}</span><h2 style={{margin:"12px 0 2px"}}>{shift?`${shift.shiftCode||""} · ${shift.shiftName}`:"Ca làm hôm nay"}</h2><p className="emp-muted">{shift?.positionName||profile?.position} · {shift?.branchName||profile?.branchName}</p><div className="emp-time-row"><div><small>Bắt đầu</small><strong>{time(shift?.startTime)}</strong></div><span className="emp-time-line"/><div><small>Kết thúc</small><strong>{time(shift?.endTime)}</strong></div></div></section>
 <div className="emp-card"><b>{hours.toFixed(1)} giờ</b><span className="emp-muted"> · Tổng lịch làm tuần này ({schedules.length} ca)</span></div>
 {registration&&<Link className="emp-card registration-home-banner" to="/employee/shift-registration"><FiPlusCircle/><div><b>{registration.canRegister?"Đăng ký lịch tuần sau":"Đợt đăng ký ca"}</b><small>{registration.canRegister?`Hạn đăng ký: ${new Date(registration.registrationCloseAt).toLocaleString("vi-VN")}`:"Đã đóng đăng ký"}</small></div><span className={`emp-badge ${registration.canRegister?"warn":""}`}>{registration.canRegister?"Mới":registration.status}</span></Link>}
 <div className="emp-section-head"><h2>Tiện ích công việc</h2></div><section className="emp-action-grid">{actions.map(([to,label,Icon])=><Link className="emp-action" to={to} key={to}><Icon/><span>{label}</span></Link>)}</section>
 <div className="emp-section-head"><h2>Thông báo mới</h2><Link to="/employee/notifications">Xem tất cả</Link></div><section className="emp-card">{notices.length?<div className="emp-list">{notices.map(n=><div className="emp-list-item" key={n.id}><span className="emp-dot"/><div><b>{n.title}</b><small>{n.content}</small><small>{shortDate(n.createdAt)}</small></div></div>)}</div>:<div className="emp-empty"><FiBell/><div>Chưa có thông báo mới</div></div>}</section></div>}
