import { useEffect, useMemo, useState } from "react";
import { FiDollarSign } from "react-icons/fi";
import { employeeApi } from "../../api/services";
import { apiError, dateKey, money, time } from "../../utils/employeeFormat";
export default function ExpensesPage(){const [date,setDate]=useState(dateKey(new Date())),[items,setItems]=useState([]),[categories,setCategories]=useState([]),[form,setForm]=useState({categoryId:"",amount:"",title:"",note:""}),[message,setMessage]=useState(""),[error,setError]=useState("");
  const load=()=>employeeApi.expenses(date).then(r=>{setItems(r.data||[]);setCategories(r.categories||[]);setForm(f=>({...f,categoryId:f.categoryId||String(r.categories?.[0]?.id||"")}))}).catch(e=>setError(apiError(e)));useEffect(load,[date]);
  const total=useMemo(()=>items.reduce((s,x)=>s+Number(x.amount),0),[items]);async function submit(e){e.preventDefault();try{const r=await employeeApi.createExpense({...form,categoryId:Number(form.categoryId),amount:Number(form.amount)});setMessage(r.message);setForm(f=>({...f,amount:"",title:"",note:""}));load()}catch(x){setError(apiError(x))}}
  return <div>{message&&<div className="emp-toast">{message}</div>}{error&&<div className="emp-error">{error}</div>}<form className="emp-card emp-form" onSubmit={submit}><h2>Ghi nhận chi phí</h2><label>Ngày<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Loại chi phí<select required value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Chọn loại</option>{categories.map(x=><option key={x.id} value={x.id}>{x.categoryName}</option>)}</select></label><div className="emp-form-grid"><label>Số tiền<input required min="1" type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Nội dung<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label></div><label>Ghi chú<textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><button className="emp-button">Lưu chi phí</button></form>
    <div className="emp-section-head"><h2>Chi phí trong ngày</h2><b>{money(total)}</b></div><section className="emp-card">{items.length?<div className="emp-list">{items.map(x=><div className="emp-list-item" key={x.id}><FiDollarSign/><div><b>{x.title}</b><small>{x.categoryName} · {time(x.expenseDate)}</small></div><b>{money(x.amount)}</b></div>)}</div>:<div className="emp-empty">Chưa có chi phí</div>}</section></div>}
