import { useMemo, useState } from "react";
import { FiCheckCircle, FiMinus, FiPlus, FiSearch, FiShoppingCart, FiTrash2, FiX } from "react-icons/fi";
import { formatMoney, initialOrders, products, readStorage, writeStorage } from "../../data/employeeData";

const categories=["Tất cả",...new Set(products.map(item=>item.category))];
export default function PosPage(){
  const [query,setQuery]=useState(""),[category,setCategory]=useState("Tất cả"),[cart,setCart]=useState([]),[orderType,setOrderType]=useState("Tại quầy"),[payment,setPayment]=useState("Tiền mặt"),[success,setSuccess]=useState("");
  const filtered=useMemo(()=>products.filter(item=>(category==="Tất cả"||item.category===category)&&item.name.toLowerCase().includes(query.toLowerCase())),[query,category]);
  const subtotal=cart.reduce((sum,item)=>sum+item.price*item.qty,0),discount=subtotal>=300000?20000:0,total=subtotal-discount;
  function add(product){setCart(current=>{const found=current.find(x=>x.id===product.id);return found?current.map(x=>x.id===product.id?{...x,qty:x.qty+1}:x):[...current,{...product,qty:1}]})}
  function quantity(id,amount){setCart(current=>current.map(x=>x.id===id?{...x,qty:x.qty+amount}:x).filter(x=>x.qty>0))}
  function submit(){if(!cart.length)return;const orders=readStorage("employeeOrders",initialOrders);const id=`DG-${1043+orders.filter(x=>String(x.id).startsWith("DG-")).length}`;writeStorage("employeeOrders",[{id,time:new Date().toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"}),total,type:orderType,status:"Đơn mới",items:cart.reduce((n,x)=>n+x.qty,0),payment},...orders]);setSuccess(`Đã tạo đơn ${id} thành công`);setCart([]);setTimeout(()=>setSuccess(""),3500)}
  return <div className="pos-page">{success&&<div className="app-toast"><FiCheckCircle/><div><b>Tạo đơn thành công</b><span>{success}</span></div><button onClick={()=>setSuccess("")}><FiX/></button></div>}<section className="pos-catalog"><div className="employee-page-title"><div><h1>Bán hàng</h1><p>Chọn món để thêm nhanh vào đơn.</p></div><span className="pos-clock">{new Date().toLocaleDateString("vi-VN")}</span></div><div className="pos-search"><FiSearch/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm món ăn, đồ uống..."/></div><div className="category-tabs">{categories.map(item=><button className={category===item?"active":""} onClick={()=>setCategory(item)} key={item}>{item}</button>)}</div><div className="product-grid">{filtered.map(item=><button className="product-card" onClick={()=>add(item)} key={item.id}><span className="product-photo">{item.image}</span><span className="product-info"><small>{item.category}</small><b>{item.name}</b><strong>{formatMoney(item.price)}</strong></span><i><FiPlus/></i></button>)}</div></section><aside className="pos-cart"><div className="pos-cart-head"><div><FiShoppingCart/><b>Đơn hiện tại</b></div><span>{cart.reduce((n,x)=>n+x.qty,0)} món</span></div><div className="order-types">{["Tại quầy","Mang đi","Giao hàng"].map(x=><button className={orderType===x?"active":""} onClick={()=>setOrderType(x)} key={x}>{x}</button>)}</div><div className="cart-items">{!cart.length?<div className="empty-cart"><FiShoppingCart/><b>Chưa có món nào</b><p>Chạm vào món bên trái để thêm</p></div>:cart.map(item=><article key={item.id}><span>{item.image}</span><div><b>{item.name}</b><small>{formatMoney(item.price)}</small><div className="quantity"><button onClick={()=>quantity(item.id,-1)}><FiMinus/></button><strong>{item.qty}</strong><button onClick={()=>quantity(item.id,1)}><FiPlus/></button></div></div><button className="remove-item" onClick={()=>setCart(x=>x.filter(p=>p.id!==item.id))}><FiTrash2/></button></article>)}</div><div className="cart-summary"><p><span>Tạm tính</span><b>{formatMoney(subtotal)}</b></p><p><span>Giảm giá</span><b className="positive">-{formatMoney(discount)}</b></p><p className="cart-total"><span>Tổng tiền</span><b>{formatMoney(total)}</b></p><label>Phương thức thanh toán<select value={payment} onChange={e=>setPayment(e.target.value)}><option>Tiền mặt</option><option>Chuyển khoản</option><option>Ví điện tử</option></select></label><button disabled={!cart.length} className="btn btn-primary confirm-order" onClick={submit}>Xác nhận đơn · {formatMoney(total)}</button></div></aside></div>
}
