import {useEffect,useState} from "react";
import {useOutletContext} from "react-router-dom";
import {FiCamera,FiEdit3,FiLogOut,FiSave} from "react-icons/fi";
import VietnamDateInput from "../../components/VietnamDateInput";
import {vietnamDateTime} from "../../utils/vietnamTime";
import {profileApi} from "../../api/services";
import {shortDate} from "../../utils/employeeFormat";

const date=value=>value?String(value).slice(0,10):"";
const fields=["phone","birthDate","gender","address","identityNumber","identityIssueDate","identityIssuePlace","bankAccountNumber","bankName","bankBranch"];

export default function ProfilePage(){
 const ctx=useOutletContext(),[profile,setProfile]=useState(ctx.profile),[form,setForm]=useState({}),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[avatarSaving,setAvatarSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>setProfile(ctx.profile),[ctx.profile]);
 useEffect(()=>{if(profile)setForm(Object.fromEntries(fields.map(key=>[key,key.toLowerCase().includes("date")?date(profile[key]):profile[key]||""])))},[profile]);
 if(ctx.loading)return <div className="emp-card emp-empty">Đang tải hồ sơ...</div>;
 if(!profile)return <div className="emp-card emp-error">{ctx.profileError||"Không tải được hồ sơ. Vui lòng tải lại trang."}</div>;
 const set=(key,value)=>setForm(current=>({...current,[key]:value}));
 const initials=profile.fullName.split(/\s+/).slice(-2).map(value=>value[0]).join("").toUpperCase();
 async function submit(event){event.preventDefault();setSaving(true);setError("");try{const response=await profileApi.updatePersonal(form),fresh=await profileApi.get();setProfile(fresh.data);ctx.setProfile?.(fresh.data);setMessage(response.message);setEditing(false)}catch(requestError){setError(requestError.response?.data?.message||"Không thể gửi hồ sơ")}finally{setSaving(false)}}
 async function changeAvatar(event){const file=event.target.files?.[0];event.target.value="";if(profile.profileUpdateLocked)return setError("Admin đã khóa quyền cập nhật hồ sơ");if(!file)return;if(file.size>5*1024*1024)return setError("Ảnh đại diện không được lớn hơn 5 MB");setAvatarSaving(true);setError("");try{const response=await profileApi.updateAvatar(file),fresh=await profileApi.get();setProfile(fresh.data);ctx.setProfile?.(fresh.data);setMessage(response.message)}catch(requestError){setError(requestError.response?.data?.message||"Không thể cập nhật ảnh đại diện")}finally{setAvatarSaving(false)}}
 const locked=(label,value)=><div><small>{label}</small><b>{value||"Chưa cập nhật"}</b><em>Không thể thay đổi</em></div>;
 return <div className="employee-profile-page">
  {message&&<div className="emp-toast">{message}</div>}{error&&<div className="emp-error">{error}</div>}
  <section className="emp-card profile-identity"><div className="profile-avatar-editor"><div className="emp-avatar">{profile.avatarUrl?<img src={profile.avatarUrl} alt={`Ảnh đại diện ${profile.fullName}`}/>:initials}</div><label className={`profile-avatar-button ${profile.profileUpdateLocked?"locked":""}`} title={profile.profileUpdateLocked?"Admin đã khóa cập nhật hồ sơ":"Cập nhật ảnh đại diện"}><FiCamera/><input type="file" accept="image/jpeg,image/png,image/webp" onChange={changeAvatar} disabled={avatarSaving||profile.profileUpdateLocked}/></label></div><small className="profile-avatar-note">{profile.profileUpdateLocked?"Hồ sơ đang bị Admin khóa cập nhật":avatarSaving?"Đang tải ảnh...":"Chạm biểu tượng máy ảnh để đổi ảnh đại diện"}</small><h2>{profile.fullName}</h2><p>{profile.employeeCode} · {profile.position}</p></section>
  <section className="emp-card profile-locked-info"><header><h3>Thông tin nhân viên</h3><small>Thông tin do Admin quản lý</small></header><div className="profile-locked-grid">{locked("Họ và tên",profile.fullName)}{locked("Mã nhân viên",profile.employeeCode)}{locked("Email / Gmail",profile.email)}{locked("Chức vụ",profile.position)}{locked("Hình thức làm việc",profile.employmentType==="part_time"?"Part-time":profile.employmentType==="full_time"?"Full-time":"Chưa cập nhật")}{locked("Chi nhánh",profile.branchName)}{locked("Ngày vào làm",shortDate(profile.hireDate))}</div></section>
  <form className="emp-card profile-personal-form" onSubmit={submit}><header><div><h3>Cập nhật hồ sơ</h3><small>{profile.profileUpdateLocked?"Admin đã khóa quyền cập nhật":"Điền thông tin và gửi lên Admin kiểm tra"}</small></div><button type="button" className="emp-button secondary" disabled={profile.profileUpdateLocked} onClick={()=>setEditing(value=>!value)}><FiEdit3/> {profile.profileUpdateLocked?"Đã khóa":editing?"Hủy sửa":"Cập nhật"}</button></header><fieldset disabled={profile.profileUpdateLocked||!editing||saving}>
   <section className="profile-form-section"><h4><span>1</span> Thông tin cá nhân</h4><div className="profile-form-grid"><label>Số điện thoại<input inputMode="numeric" value={form.phone||""} onChange={e=>set("phone",e.target.value)}/></label><label>Ngày sinh<VietnamDateInput value={form.birthDate||""} onChange={e=>set("birthDate",e.target.value)}/></label><label>Giới tính<select value={form.gender||""} onChange={e=>set("gender",e.target.value)}><option value="">Chưa chọn</option><option value="male">Nam</option><option value="female">Nữ</option><option value="other">Khác</option></select></label><label>Địa chỉ<input value={form.address||""} onChange={e=>set("address",e.target.value)}/></label></div></section>
   <section className="profile-form-section"><h4><span>2</span> Căn cước công dân</h4><div className="profile-form-grid"><label>Số CCCD<input inputMode="numeric" value={form.identityNumber||""} onChange={e=>set("identityNumber",e.target.value)}/></label><label>Ngày cấp<VietnamDateInput value={form.identityIssueDate||""} onChange={e=>set("identityIssueDate",e.target.value)}/></label><label className="profile-field-wide">Nơi cấp<input value={form.identityIssuePlace||""} onChange={e=>set("identityIssuePlace",e.target.value)}/></label></div></section>
   <section className="profile-form-section"><h4><span>3</span> Tài khoản ngân hàng</h4><div className="profile-form-grid"><label>Số tài khoản ngân hàng<input inputMode="numeric" value={form.bankAccountNumber||""} onChange={e=>set("bankAccountNumber",e.target.value)}/></label><label>Tên ngân hàng<input value={form.bankName||""} onChange={e=>set("bankName",e.target.value)} placeholder="ACB, MB, Vietcombank..."/></label><label className="profile-field-wide">Chi nhánh ngân hàng<input value={form.bankBranch||""} onChange={e=>set("bankBranch",e.target.value)}/></label></div></section>
  </fieldset>{profile.profileSubmittedAt&&<p className="profile-last-submit">Gửi Admin gần nhất: {vietnamDateTime(profile.profileSubmittedAt)}</p>}{editing&&<button className="emp-button profile-submit" disabled={saving}><FiSave/> {saving?"Đang gửi...":"Gửi thông tin lên Admin"}</button>}</form>
  <button className="emp-button danger" onClick={ctx.logout}><FiLogOut/> Đăng xuất</button>
 </div>;
}
