import { useEffect, useMemo, useState } from "react";
import { employeeApi } from "../../api/services";
import { apiError, money } from "../../utils/employeeFormat";
const initial={cashRevenue:"",transferRevenue:"",ewalletRevenue:"",deliveryRevenue:"",actualCash:"",note:""};
export default function ShiftClosingPage(){const [session,setSession]=useState(null),[form,setForm]=useState(initial),[locked,setLocked]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  useEffect(()=>{employeeApi.shiftSession().then(r=>setSession(r.data)).catch(e=>setError(apiError(e)))},[]);
  const total=useMemo(()=>["cashRevenue","transferRevenue","ewalletRevenue","deliveryRevenue"].reduce((s,k)=>s+Number(form[k]||0),0),[form]);
  const expected=Number(session?.openingCash||0)+Number(form.cashRevenue||0),difference=Number(form.actualCash||0)-expected;
  async function submit(e){e.preventDefault();if(!window.confirm("Xác nhận đóng ca? Sau khi đóng, dữ liệu sẽ được khóa."))return;try{const r=await employeeApi.closeShift(Object.fromEntries(Object.entries(form).map(([k,v])=>[k,k==="note"?v:Number(v||0)])));setMessage(r.message);setLocked(true)}catch(x){setError(apiError(x))}}
  if(!session&&!error)return <div className="emp-card emp-empty">Đang kiểm tra ca...</div>;
  return <div>{message&&<div className="emp-toast">{message}</div>}{error&&<div className="emp-error">{error}</div>}{!session?<div className="emp-card emp-empty">Bạn cần mở ca trước khi đóng ca.</div>:<form className="emp-card emp-form" onSubmit={submit}><span className="emp-badge success">Ca đang mở</span><h2>Đối soát cuối ca</h2><div className="emp-form-grid">{[["cashRevenue","Doanh thu tiền mặt"],["transferRevenue","Chuyển khoản"],["ewalletRevenue","Ví điện tử"],["deliveryRevenue","Giao hàng"],["actualCash","Tiền mặt thực tế"]].map(([key,label])=><label key={key}>{label}<input disabled={locked} type="number" min="0" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><div className="emp-list"><div className="emp-list-item"><div><small>Tiền đầu ca</small><b>{money(session.openingCash)}</b></div></div><div className="emp-list-item"><div><small>Tổng doanh thu</small><b>{money(total)}</b></div></div><div className="emp-list-item"><div><small>Tiền mặt dự kiến (chưa trừ chi phí hệ thống)</small><b>{money(expected)}</b></div></div><div className="emp-list-item"><div><small>Chênh lệch tạm tính</small><b>{money(difference)}</b></div></div></div><label>Ghi chú cuối ca<textarea disabled={locked} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><button className="emp-button" disabled={locked}>Xác nhận đóng ca</button></form>}</div>}
