import {useEffect,useMemo,useState} from 'react';
import {employeeApi,shiftInventoryApi} from '../../api/services';
import '../../styles/shift-inventory.css';

const errorText=error=>error?.response?.data?.message||error?.message||'Không thể tải sổ xuất nguyên liệu';
const qty=value=>new Intl.NumberFormat('vi-VN',{maximumFractionDigits:3}).format(Number(value||0));

export default function ShiftInventoryPage(){
 const isSandbox=import.meta.env.VITE_APP_ENV==='sandbox';
 const [data,setData]=useState(null),[schedules,setSchedules]=useState([]),[scheduleId,setScheduleId]=useState('');
 const [usage,setUsage]=useState({}),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const selectedSchedule=schedules.find(item=>String(item.scheduleId)===String(scheduleId));
 const load=async(selected=selectedSchedule)=>{try{setError('');const params=selected?{date:selected.workDate,scheduleId:selected.scheduleId}:undefined;const response=await shiftInventoryApi.current(params);setData(response.data)}catch(err){setError(errorText(err));setData(null)}};
 useEffect(()=>{const initialise=async()=>{if(!isSandbox)return load();try{const response=await employeeApi.attendanceTestSchedules(),items=response.data||[];setSchedules(items);const remembered=localStorage.getItem('sandbox-active-schedule-id')||localStorage.getItem('sandbox-shift-inventory-schedule-id');const selected=items.find(item=>String(item.scheduleId)===remembered)||items[0];if(selected){setScheduleId(String(selected.scheduleId));await load(selected)}}catch(err){setError(errorText(err))}};initialise()},[isSandbox]);
 const changeSchedule=async value=>{const selected=schedules.find(item=>String(item.scheduleId)===value);setScheduleId(value);setUsage({});setMessage('');if(!selected)return;localStorage.setItem('sandbox-active-schedule-id',value);localStorage.setItem('sandbox-shift-inventory-schedule-id',value);localStorage.setItem('sandbox-shift-inventory-date',selected.workDate);await load(selected)};
 const scheduleLabel=item=>`${new Date(`${item.workDate}T00:00:00`).toLocaleDateString('vi-VN',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})} — Ca ${item.shiftCode} (${item.startTime?.slice(0,5)}–${item.endTime?.slice(0,5)})`;
 const inventory=data?.inventory,operation=data?.operation,items=inventory?.items||[];
 const totalExport=useMemo(()=>Object.values(usage).reduce((sum,value)=>sum+Number(value||0),0),[usage]);
 const run=async callback=>{try{setBusy(true);setError('');const response=await callback();setMessage(response.message||'Đã lưu');setUsage({});setNote('');await load(selectedSchedule)}catch(err){setError(errorText(err))}finally{setBusy(false)}};
 const start=()=>run(()=>shiftInventoryApi.start({scheduleId:operation.scheduleId,businessDate:operation.businessDate}));
 const submit=()=>{const exported=items.map(item=>({productId:item.product_id,quantity:Number(usage[item.product_id]||0)})).filter(item=>item.quantity>0);if(!exported.length){setError('Hãy nhập ít nhất một số lượng xuất trong ca.');return}const requestKey=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;run(()=>shiftInventoryApi.recordUsage(inventory.id,{requestKey,note,items:exported}))};
 const picker=isSandbox&&<section className="si-card si-schedule-picker"><div><strong>Ngày kiểm kho theo lịch làm</strong><small>Chỉ hiển thị lịch chính thức đã công bố và đã chấm công.</small></div><select value={scheduleId} onChange={event=>changeSchedule(event.target.value)} disabled={busy}><option value="">Chọn ngày và ca</option>{schedules.map(item=><option key={item.scheduleId} value={item.scheduleId}>{scheduleLabel(item)}</option>)}</select></section>;
 if(!operation)return <div className="si-page">{picker}<div className="si-empty"><h2>Chưa thể ghi xuất nguyên liệu</h2><p>Bạn cần có lịch chính thức và đã chấm công vào ca.</p>{error&&<p className="si-error">{error}</p>}</div></div>;
 if(!inventory)return <div className="si-page">{picker}<section className="si-hero"><span className="si-badge">XUẤT TRONG CA</span><h2>Sổ xuất nguyên liệu</h2><p>{operation.businessDate} · Ca {operation.operationShift==='morning'?'sáng':'chiều'}</p></section>{error&&<p className="si-error">{error}</p>}<section className="si-card si-onboarding"><h3>Bắt đầu ghi xuất nguyên liệu</h3><p>Hệ thống sẽ lấy toàn bộ nguyên liệu đang hoạt động trong Quản lý sản phẩm.</p><button className="si-primary" disabled={busy} onClick={start}>{busy?'Đang mở...':'Mở sổ xuất trong ca'}</button></section></div>;
 const locked=['WAITING_HANDOVER','CLOSED'].includes(inventory.status);
 return <div className="si-page">{picker}<section className="si-hero"><span className="si-badge">XUẤT TRONG CA</span><h2>Sổ xuất nguyên liệu ca {inventory.operation_shift_code==='morning'?'sáng':'chiều'}</h2><p>{String(inventory.business_date).slice(0,10)} · {inventory.branchName}</p></section>{message&&<p className="si-ok">{message}</p>}{error&&<p className="si-error">{error}</p>}<div className="si-summary"><div><small>Nguyên liệu</small><b>{items.length}</b></div><div><small>Tổng đang nhập</small><b>{qty(totalExport)}</b></div></div><section className="si-card shift-usage-card"><div className="si-section-title"><div><h3>Nguyên liệu xuất sử dụng</h3><p>Chỉ nhập những nguyên liệu đã lấy ra sử dụng trong ca.</p></div></div><div className="si-table shift-usage-table"><div className="si-row shift-usage-row si-head"><b>Nguyên liệu</b><b>Nhóm</b><b>ĐVT</b><b>Tồn hiện tại</b><b>Xuất trong ca</b></div>{items.map(item=><div className="si-row shift-usage-row" key={item.product_id}><strong className="shift-usage-product">{item.productName}<small>{item.productCode}</small></strong><span className="shift-usage-group">{item.categoryName}</span><span className="shift-usage-unit">{item.unitName}</span><span className="shift-usage-stock"><small>Tồn hiện tại</small><b>{qty(item.systemQuantity)}</b></span><label className="shift-usage-input"><small>Xuất trong ca</small>{locked?<span>—</span>:<input type="number" min="0" max={Number(item.systemQuantity||0)} step="0.001" placeholder="0" value={usage[item.product_id]??''} onFocus={event=>event.target.select()} onChange={event=>setUsage(current=>({...current,[item.product_id]:event.target.value}))}/>}</label></div>)}</div>{!locked&&<><label className="shift-usage-note">Ghi chú chung<textarea placeholder="Mục đích xuất hoặc ghi chú nếu có" value={note} onChange={event=>setNote(event.target.value)}/></label><div className="si-actions"><button className="si-primary" disabled={busy||totalExport<=0} onClick={submit}>{busy?'Đang lưu...':'Xác nhận xuất trong ca'}</button></div></>}</section></div>;
}
